# Lista de Exercícios — Dataframes

Esta lista tem como objetivo praticar os principais recursos construção de Dataframes em Python visto na última aula.

### Tarefa para entregar

* 1. Fazer um Script em Jupyter de um robô de coleta de dados com o Selenium. Ele deve coletar todas as planilhas do site da receita federal, do site:
  * "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/copy_of_arrecadacao-das-receitas-administradas-pela-rfb-por-municipio"

* 2. No mesmo Script, você deve realizar uma programação completa para unificar todas as planilhas em uma estrutura de dados em painel. 
  * Dicas: Lembre de adicionar uma coluna com o ano da amostra, e uma coluna com um código identificador - Código do IBGE. Verifique o procedimento de criação do identificador que realizamos ao fazer o web scraping com o pandas em aula.

* Entregue o arquivo `.ipynb` por e-mail (daniel.uhr@gmail.com) até o dia **28/04/2024**.

**Bom trabaho!**

In [6]:
#1.A
from selenium import webdriver
from selenium.webdriver.common.by import By

navegador = webdriver.Chrome()
navegador.get('https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/copy_of_arrecadacao-das-receitas-administradas-pela-rfb-por-municipio')

#Click on cookie message! Otherwise, next code does not execute.
print("Click on the cookie message! Otherwise, next code does not execute.")

Click on the cookie message! Otherwise, next code does not execute.

In [7]:
#1.B
#downloads excel arquives to download folder

from selenium.webdriver.common.by import By

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[1]/th/a').click()
#ate 2017   //*[@id="a5c9477ba62b4003a31cfd35b30d16db"]/div/table/tbody/tr[1]/th/a

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[2]/th/span/a').click()
#2018       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[2]/th/span/a

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[3]/th/span[1]/a').click()
#2019       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[3]/th/span[1]/a

#2020       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[4]/th/span/span/a[1]
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[4]/th/span/span/a[1]').click()

#2021       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[5]/th/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[5]/th/span/span/a').click()

#2022       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[6]/th/span/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[6]/th/span/span/span/a').click()

#2023       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[7]/th/span/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[7]/th/span/span/span/a').click()

ElementClickInterceptedException: Message: element click intercepted: Element <a title="" href="https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/copy_of_arrecadacao-das-receitas-administradas-pela-rfb-por-municipio/arrecadacao-das-receitas-administradas-pela-rfb/arrecadacao-da-receita-administrada-pela-rfb-por-municipio-2005-a-2017.xlsx" data-mce-href="resolveuid/c79fd95501374a8fb3e03d461820566f" class="internal-link" target="_self">...</a> is not clickable at point (244, 386). Other element would receive the click: <barra-govbr class="width100 shadow-none show-contrast-toggle" style="width: 100%;" id="barra-govbr" titulo="Ministério da Fazenda" signinhref="/govbrportal/inicializacao-autenticacao-openid.html" signouthref="/govbrportal/logout.html" linktitulo="https://www.gov.br/fazenda" linklogo="https://www.gov.br/pt-br" idiomas="" idiomaativo="" linksdosistema="[{&quot;title&quot;:&quot;Órgãos do Governo&quot;,&quot;href&quot;:&quot;https://www.gov.br/pt-br/orgaos-do-governo&quot;},{&quot;title&quot;:&quot;Acesso à Informação&quot;,&quot;href&quot;:&quot;https://www.gov.br/acessoainformacao/pt-br&quot;},{&quot;title&quot;:&quot;Legislação&quot;,&quot;href&quot;:&quot;http://www4.planalto.gov.br/legislacao&quot;},{&quot;title&quot;:&quot;Acessibilidade&quot;,&quot;href&quot;:&quot;https://www.gov.br/governodigital/pt-br/acessibilidade-digital&quot;}]" contrastactive="false">...</barra-govbr>
  (Session info: chrome=135.0.7049.115)
Stacktrace:
	GetHandleVerifier [0x00007FF67B82EFA5+77893]
	GetHandleVerifier [0x00007FF67B82F000+77984]
	(No symbol) [0x00007FF67B5F91BA]
	(No symbol) [0x00007FF67B6570A9]
	(No symbol) [0x00007FF67B654A62]
	(No symbol) [0x00007FF67B651B01]
	(No symbol) [0x00007FF67B650A01]
	(No symbol) [0x00007FF67B642134]
	(No symbol) [0x00007FF67B67712A]
	(No symbol) [0x00007FF67B6419E6]
	(No symbol) [0x00007FF67B677340]
	(No symbol) [0x00007FF67B69F07F]
	(No symbol) [0x00007FF67B676F03]
	(No symbol) [0x00007FF67B640328]
	(No symbol) [0x00007FF67B641093]
	GetHandleVerifier [0x00007FF67BAE7B6D+2931725]
	GetHandleVerifier [0x00007FF67BAE2132+2908626]
	GetHandleVerifier [0x00007FF67BB000F3+3031443]
	GetHandleVerifier [0x00007FF67B8491EA+184970]
	GetHandleVerifier [0x00007FF67B85086F+215311]
	GetHandleVerifier [0x00007FF67B836EC4+110436]
	GetHandleVerifier [0x00007FF67B837072+110866]
	GetHandleVerifier [0x00007FF67B81D479+5401]
	BaseThreadInitThunk [0x00007FFA342CE8D7+23]
	RtlUserThreadStart [0x00007FFA354914FC+44]

In [ ]:
# unificar todas as planilhas em uma estrutura de dados em painel. 
#  * Dicas: Lembre de adicionar uma coluna com o ano da amostra, 
#   * e uma coluna com um código identificador - Código do IBGE. 
#   Verifique o procedimento de criação do identificador que realizamos ao fazer o web scraping com o pandas em aula.

import pandas as pd

# Caminho do arquivo
file_path = r"C:\Users\johan\Downloads\arrecadacao-da-receita-administrada-pela-rfb-por-municipio-2005-a-2017.xlsx"

# Ler todas as abas disponíveis no arquivo
abas_disponiveis = pd.ExcelFile(file_path).sheet_names

# Criar um dicionário para armazenar os DataFrames com nomes ajustados
df_dict = {}

# Padronizar manualmente os nomes das abas
for aba in abas_disponiveis:
    aba_formatada = aba.strip()  # Remove espaços extras
    
    if aba_formatada.lower() == "gps":
        aba_padronizada = "GPS"
    elif aba_formatada.lower() == "darf":
        aba_padronizada = "DARF"
    elif aba_formatada.lower() == "total":
        aba_padronizada = "Total"
    else:
        aba_padronizada = aba_formatada  # Mantém outros nomes inalterados
    
    # Ler a aba com o nome original e salvar no dicionário com o nome padronizado
    df_dict[aba_padronizada] = pd.read_excel(file_path, sheet_name=aba, engine="openpyxl", skiprows=5)

# Exibir abas carregadas
df_dict.keys() # Confirma nomes ajustados

dict_keys(['DARF', 'GPS', 'Total'])

In [ ]:
# Criar DataFrame inicial vazio
list17 = None

# Aplicar melt() em todas as abas antes da unificação
for aba, df in df_dict.items():
    print(f"Length {aba}: {len(df)}")
    
    # Padronizar nome das colunas
    df.rename(columns={'MUNICIPIOS': 'Município', 'ARRECADAÇÃO': 'Arrecadação'}, inplace=True)

    # Transformar de wide para long
    df_melted = df.melt(id_vars=["Município", "UF"], var_name="Ano", value_name=f"Arrecadação_{aba}")

    # Gravar de onde vem o valor
    df_melted["Fonte"] = aba

    # Unificar corretamente usando merge
    if list17 is None:
        list17 = df_melted  # Primeiro DataFrame define a base
    else:
        list17 = list17.merge(df_melted, on=["Município", "UF", "Ano"], how="outer")

# Verificar os nomes das abas após a importação

print(list17.head())

Length DARF: 5572
Length GPS: 5566
Length Total: 5584
         Município  UF   Ano  Arrecadação_DARF Fonte_x  Arrecadação_GPS  \
0  ABADIA DE GOIAS  GO  2005         748293.01    DARF        644826.24
1  ABADIA DE GOIAS  GO  2006         743933.43    DARF        815836.10
2  ABADIA DE GOIAS  GO  2007         947889.34    DARF       1130922.71
3  ABADIA DE GOIAS  GO  2008        1326710.17    DARF       1419804.58
4  ABADIA DE GOIAS  GO  2009        1481737.43    DARF       1630513.33

  Fonte_y  Arrecadação_Total  Fonte
0     GPS         1393119.25  Total
1     GPS         1559769.53  Total
2     GPS         2078812.05  Total
3     GPS         2746514.75  Total
4     GPS         3112250.76  Total

In [14]:
import pandas as pd

# Lista dos anos disponíveis
anos = [2018, 2019, 2020, 2021, 2022, 2023]

# Criar um dicionário para armazenar os DataFrames de cada ano
df_anos = {}

# Processar todos os arquivos em um loop
for ano in anos:
    print(f"📂 Processando {ano}...")

    # Definir o caminho do arquivo
    file_path = fr"C:\Users\johan\Downloads\arrecadacao-da-receita-administrada-pela-rfb-por-municipio-{ano}.xlsx"

    # Ler todas as abas disponíveis no arquivo
    abas_disponiveis = pd.ExcelFile(file_path).sheet_names

    # Criar um dicionário para armazenar os DataFrames de cada aba do ano
    df_dict = {}

    # Processar cada aba (DARF, GPS, Total)
    for aba in abas_disponiveis:
        aba_formatada = aba.strip()
        
        if aba_formatada.lower() == "gps":
            aba_padronizada = "GPS"
        elif aba_formatada.lower() == "darf":
            aba_padronizada = "DARF"
        elif aba_formatada.lower() == "total":
            aba_padronizada = "Total"
        else:
            aba_padronizada = aba_formatada  

        # Ler cada aba do arquivo e armazenar no dicionário
        df_dict[aba_padronizada] = pd.read_excel(file_path, sheet_name=aba, engine="openpyxl", skiprows=5)

    # Criar DataFrame consolidado para este ano
    df_final = None

    # Aplicar transformação `melt()` em todas as abas antes de armazenar
    for aba, df in df_dict.items():
        print(f"✅ Processando aba {aba} ({ano}): {len(df)} registros")

        # Padronizar nome das colunas
        df.rename(columns={'MUNICÍPIOS': 'Município', 'ARRECADAÇÃO': 'Arrecadação'}, inplace=True)

        # Adicionar a coluna 'Ano'
        df["Ano"] = ano

        # Transformar de wide para long
        df_melted = df.melt(id_vars=["Município", "UF", "Ano"], var_name="Categoria", value_name=f"Arrecadação_{aba}")

        # Gravar de onde vem o valor
        df_melted["Fonte"] = aba

        # Unificar corretamente usando merge
        if df_final is None:
            df_final = df_melted  # Primeiro DataFrame define a base
        else:
            df_final = df_final.merge(df_melted, on=["Município", "UF", "Ano", "Categoria"], how="outer")

    # Armazenar o resultado do ano no dicionário geral
    df_anos[ano] = df_final

    print(f"✅ Dados armazenados para {ano}!")

# Agora, `df_anos[2018]`, `df_anos[2019]`, etc. contêm os DataFrames de cada ano separadamente!

# visualizar
print(df_anos[2018].head())
print(df_anos[2019].head())
print(df_anos[2020].head())
print(df_anos[2021].head())
print(df_anos[2022].head())
print(df_anos[2023].head())

📂 Processando 2018...

C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

✅ Processando aba DARF (2018): 5572 registros
✅ Processando aba GPS (2018): 5568 registros
✅ Processando aba Total (2018): 5578 registros
✅ Dados armazenados para 2018!
📂 Processando 2019...
✅ Processando aba GPS (2019): 5568 registros
✅ Processando aba DARF (2019): 5572 registros
✅ Processando aba Total (2019): 5574 registros
✅ Dados armazenados para 2019!
📂 Processando 2020...
✅ Processando aba GPS (2020): 5568 registros
✅ Processando aba DARF (2020): 5572 registros
✅ Processando aba Total (2020): 5574 registros
✅ Dados armazenados para 2020!
📂 Processando 2021...
✅ Processando aba GPS (2021): 5568 registros
✅ Processando aba DARF (2021): 5572 registros
✅ Processando aba Total (2021): 5574 registros
✅ Dados armazenados para 2021!
📂 Processando 2022...
✅ Processando aba GPS (2022): 5568 registros
✅ Processando aba DARF (2022): 5572 registros
✅ Processando aba Total (2022): 5574 registros
✅ Dados armazenados para 2022!
📂 Processando 2023...
✅ Processando aba GPS (2023): 5552 registros
✅ Processando aba DARF (2023): 5572 registros
✅ Processando aba Total (2023): 5573 registros
✅ Dados armazenados para 2023!
             Município  UF   Ano    Categoria  Arrecadação_DARF Fonte_x  \
0      ABADIA DE GOIAS  GO  2018  Arrecadação        9509713.49    DARF
1  ABADIA DOS DOURADOS  MG  2018  Arrecadação        3457362.00    DARF
2            ABADIANIA  GO  2018  Arrecadação        8996131.56    DARF
3               ABAETE  MG  2018  Arrecadação       16060311.20    DARF
4           ABAETETUBA  PA  2018  Arrecadação       28281622.15    DARF

   Arrecadação_GPS Fonte_y  Arrecadação_Total  Fonte
0     5.322375e+06     GPS       1.483209e+07  Total
1     5.492808e+06     GPS       8.950170e+06  Total
2     8.795502e+06     GPS       1.779163e+07  Total
3     1.919428e+07     GPS       3.525459e+07  Total
4     3.127840e+07     GPS       5.956002e+07  Total
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2019  Arrecadação     3.797903e+06     GPS
1  ABADIA DOS DOURADOS  MG  2019  Arrecadação     4.996573e+06     GPS
2            ABADIANIA  GO  2019  Arrecadação     5.305279e+06     GPS
3               ABAETE  MG  2019  Arrecadação     1.156799e+07     GPS
4           ABAETETUBA  PA  2019  Arrecadação     1.805203e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       12244132.25    DARF       1.604204e+07  Total
1        4367500.58    DARF       9.364074e+06  Total
2       12388968.52    DARF       1.769425e+07  Total
3       20403566.51    DARF       3.197155e+07  Total
4       35750023.16    DARF       5.380205e+07  Total
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2020  Arrecadação       5568760.54     GPS
1  ABADIA DOS DOURADOS  MG  2020  Arrecadação       6389291.46     GPS
2            ABADIANIA  GO  2020  Arrecadação       6815920.00     GPS
3               ABAETE  MG  2020  Arrecadação      11491497.62     GPS
4           ABAETETUBA  PA  2020  Arrecadação      19918627.92     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       16515239.27    DARF        22083999.81  Total
1        4575592.99    DARF        10964884.45  Total
2       12512420.49    DARF        19328340.49  Total
3       22971308.59    DARF        34462806.21  Total
4       37645006.50    DARF        57563634.42  Total
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2021  Arrecadação     5.731301e+06     GPS
1  ABADIA DOS DOURADOS  MG  2021  Arrecadação     5.972473e+06     GPS
2            ABADIANIA  GO  2021  Arrecadação     7.187772e+06     GPS
3               ABAETE  MG  2021  Arrecadação     1.317147e+07     GPS
4           ABAETETUBA  PA  2021  Arrecadação     3.000272e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       22231269.13    DARF       2.796257e+07  Total
1        5592030.73    DARF       1.156450e+07  Total
2       19656760.35    DARF       2.684453e+07  Total
3       35392549.43    DARF       4.856402e+07  Total
4       46057901.01    DARF       7.606062e+07  Total
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2022  Arrecadação     3.413516e+06     GPS
1  ABADIA DOS DOURADOS  MG  2022  Arrecadação     3.490005e+06     GPS
2            ABADIANIA  GO  2022  Arrecadação     3.245343e+06     GPS
3               ABAETE  MG  2022  Arrecadação     7.044523e+06     GPS
4           ABAETETUBA  PA  2022  Arrecadação     1.887626e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       27662996.55    DARF       3.107651e+07  Total
1       10197772.70    DARF       1.368778e+07  Total
2       29146031.22    DARF       3.239137e+07  Total
3       47264200.43    DARF       5.430872e+07  Total
4       70958256.09    DARF       8.983451e+07  Total
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2023  Arrecadação        483977.23     GPS
1  ABADIA DOS DOURADOS  MG  2023  Arrecadação        427738.91     GPS
2            ABADIANIA  GO  2023  Arrecadação        678160.63     GPS
3               ABAETE  MG  2023  Arrecadação        878834.04     GPS
4           ABAETETUBA  PA  2023  Arrecadação        783404.63     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       32992856.91    DARF        33476834.14  Total
1       13195865.60    DARF        13623604.51  Total
2       26169372.37    DARF        26847533.00  Total
3       61532280.74    DARF        62411114.78  Total
4       81106448.13    DARF        81889852.76  Total

In [ ]:
import pandas as pd
from unidecode import unidecode

# Criar lista de municípios + UF a partir de list17 (2005-2017)
municipios_antigos = list17[["Município", "UF"]].drop_duplicates().dropna().reset_index(drop=True)

# Transformar em string e ordenar ignorando acentos
municipios_antigos["Município"] = municipios_antigos["Município"].astype(str)
municipios_antigos["UF"] = municipios_antigos["UF"].astype(str)
municipios_antigos = municipios_antigos.sort_values(by=["UF", "Município"], key=lambda x: x.apply(unidecode)).reset_index(drop=True)

# Criar lista de municípios + UF a partir de df_anos (2018-2023)
municipios_novos = pd.concat([df_anos[ano][["Município", "UF"]] for ano in df_anos], ignore_index=True).drop_duplicates().dropna().reset_index(drop=True)
municipios_novos["Município"] = municipios_novos["Município"].astype(str)
municipios_novos["UF"] = municipios_novos["UF"].astype(str)
municipios_novos = municipios_novos.sort_values(by=["UF", "Município"], key=lambda x: x.apply(unidecode)).reset_index(drop=True)

# Comparar listas de municípios
diferenca_municipios = municipios_novos.merge(municipios_antigos, on=["Município", "UF"], how="outer", indicator=True)
diferenca_municipios = diferenca_municipios[diferenca_municipios["_merge"] == "left_only"].drop(columns=["_merge"])

# Criar lista mestre combinando ambos os conjuntos
municipios_master = pd.concat([municipios_antigos, diferenca_municipios]).drop_duplicates().reset_index(drop=True)

# Exibir informações
print("✅ Municípios em list17 (2005-2017):", len(municipios_antigos))
print("✅ Municípios em df_anos (2018-2023):", len(municipios_novos))
print("✅ Diferença encontrada:", len(diferenca_municipios))
print("✅ Total de municípios na lista mestre:", len(municipios_master))
print(municipios_master.head())

✅ Municípios em list17 (2005-2017): 5584
✅ Municípios em df_anos (2018-2023): 5582
✅ Diferença encontrada: 5
✅ Total de municípios na lista mestre: 5589
      Município  UF
0         TOTAL   -
1    ACRELANDIA  AC
2  ASSIS BRASIL  AC
3     BRASILEIA  AC
4        BUJARI  AC

In [ ]:
 # Criar coluna com codigo IGBE

## Raspagem das tabelas do site
url = 'https://www.gov.br/receitafederal/dados/municipios.csv'
df_ibge = pd.read_csv(url, sep=";", encoding="latin1")

print(type(df_ibge))  # Deve ser um pandas DataFrame

## Checando o número e shape de tabelas encontradas
print(df_ibge.shape)  # Retorna (número de linhas, número de colunas)
print(df_ibge.head())

<class 'pandas.core.frame.DataFrame'>
(5571, 5)
   CÓDIGO DO MUNICÍPIO - TOM  CÓDIGO DO MUNICÍPIO - IBGE  \
0                          1                     1100106
1                          2                     1100379
2                          3                     1100205
3                          4                     1100452
4                          5                     1100122

           MUNICÍPIO - TOM         MUNICÍPIO - IBGE  UF
0            GUAJARÁ-MIRIM            Guajará-Mirim  RO
1  ALTO ALEGRE DOS PARECIS  Alto Alegre dos Parecis  RO
2              PORTO VELHO              Porto Velho  RO
3                  BURITIS                  Buritis  RO
4                JI-PARANÁ                Ji-Paraná  RO

In [ ]:
import pandas as pd

# Carregar o CSV dos municípios brasileiros do prof
url = "https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv"
municipios_ibge = pd.read_csv(url)

# Exibir as primeiras linhas
print(municipios_ibge.head())
print(municipios_ibge.shape)  # Retorna (número de linhas, número de colunas)

# Como teria que substituir o codigo_uf pela UF, vou optar por usar a outra lista, ela tbm tem uma linha a mais...?

In [ ]:
### COGIDO ANTIGO / com codigo qualquer ao inves do IGBE

# criar painel
import pandas as pd
municipios = pd.DataFrame({'Município': municipios.reset_index(drop=True)})

# criar variavel identificadora so de ordem mesmo, pra poder seguir com o exercicio
municipios['ID'] = range(1, len(municipios) + 1)
municipios.head()

             Município  ID
0      ABADIA DE GOIAS   1
1  ABADIA DOS DOURADOS   2
2            ABADIANIA   3
3               ABAETE   4
4           ABAETETUBA   5

In [ ]:
# juntar esse identificador em todas as listas utilizando 'Muncipio' como chave.
list17 = list17.merge(municipios, on='Município', how='left')
print(list17.head())
list18 = list18.merge(municipios, on='Município', how='left')
list19 = list19.merge(municipios, on='Município', how='left')
list20 = list20.merge(municipios, on='Município', how='left')
list21 = list21.merge(municipios, on='Município', how='left')
list22 = list22.merge(municipios, on='Município', how='left')
list23 = list23.merge(municipios, on='Município', how='left')
print(list18.head())
print(list19.head())
print(list20.head())
print(list21.head())
print(list22.head())
print(list23.head())

             Município  UF   Ano  Arrecadação  ID
0      ABADIA DE GOIAS  GO  2005    748293.01   1
1  ABADIA DOS DOURADOS  MG  2005    377868.56   2
2            ABADIANIA  GO  2005    533029.95   3
3               ABAETE  MG  2005   4179358.65   4
4           ABAETETUBA  PA  2005   2081937.34   5
             Município  UF  Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO   9509713.49  2018   1
1  ABADIA DOS DOURADOS  MG   3457362.00  2018   2
2            ABADIANIA  GO   8996131.56  2018   3
3               ABAETE  MG  16060311.20  2018   4
4           ABAETETUBA  PA  28281622.15  2018   5
             Município  UF   Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO  3.797903e+06  2019   1
1  ABADIA DOS DOURADOS  MG  4.996573e+06  2019   2
2            ABADIANIA  GO  5.305279e+06  2019   3
3               ABAETE  MG  1.156799e+07  2019   4
4           ABAETETUBA  PA  1.805203e+07  2019   5
             Município  UF  Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO   5568760.54  2020   1
1  ABADIA DOS DOURADOS  MG   6389291.46  2020   2
2            ABADIANIA  GO   6815920.00  2020   3
3               ABAETE  MG  11491497.62  2020   4
4           ABAETETUBA  PA  19918627.92  2020   5
             Município  UF   Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO  5.731301e+06  2021   1
1  ABADIA DOS DOURADOS  MG  5.972473e+06  2021   2
2            ABADIANIA  GO  7.187772e+06  2021   3
3               ABAETE  MG  1.317147e+07  2021   4
4           ABAETETUBA  PA  3.000272e+07  2021   5
             Município  UF   Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO  3.413516e+06  2022   1
1  ABADIA DOS DOURADOS  MG  3.490005e+06  2022   2
2            ABADIANIA  GO  3.245343e+06  2022   3
3               ABAETE  MG  7.044523e+06  2022   4
4           ABAETETUBA  PA  1.887626e+07  2022   5
             Município  UF  Arrecadação   Ano  ID
0      ABADIA DE GOIAS  GO    483977.23  2023   1
1  ABADIA DOS DOURADOS  MG    427738.91  2023   2
2            ABADIANIA  GO    678160.63  2023   3
3               ABAETE  MG    878834.04  2023   4
4           ABAETETUBA  PA    783404.63  2023   5

In [ ]:
# verificar o numero de linhas nulas 
list17

,Município,UF,Ano,Arrecadação_DARF,Fonte_x,Arrecadação_GPS,Fonte_y,Arrecadação_Total,Fonte
0,ABADIA DE GOIAS,GO,2005,748293.01,DARF,6.448262e+05,GPS,1.393119e+06,Total
1,ABADIA DE GOIAS,GO,2006,743933.43,DARF,8.158361e+05,GPS,1.559770e+06,Total
2,ABADIA DE GOIAS,GO,2007,947889.34,DARF,1.130923e+06,GPS,2.078812e+06,Total
3,ABADIA DE GOIAS,GO,2008,1326710.17,DARF,1.419805e+06,GPS,2.746515e+06,Total
4,ABADIA DE GOIAS,GO,2009,1481737.43,DARF,1.630513e+06,GPS,3.112251e+06,Total
...,...,...,...,...,...,...,...,...,...
72613,ZORTEA,SC,2013,661654.86,DARF,1.677017e+06,GPS,2.338672e+06,Total
72614,ZORTEA,SC,2014,865452.16,DARF,1.396609e+06,GPS,2.262061e+06,Total
72615,ZORTEA,SC,2015,978847.96,DARF,1.935558e+06,GPS,2.914406e+06,Total
72616,ZORTEA,SC,2016,1076423.34,DARF,1.733237e+06,GPS,2.809660e+06,Total
72617,ZORTEA,SC,2017,1220668.80,DARF,2.179870e+06,GPS,3.400539e+06,Total

In [ ]:
list17['ID'].isnull().sum()

KeyError: 'ID'

In [ ]:
df_anos[2018]

                Município  UF   Arrecadação   Ano    ID
0         ABADIA DE GOIAS  GO  9.509713e+06  2018     1
1     ABADIA DOS DOURADOS  MG  3.457362e+06  2018     2
2               ABADIANIA  GO  8.996132e+06  2018     3
3                  ABAETE  MG  1.606031e+07  2018     4
4              ABAETETUBA  PA  2.828162e+07  2018     5
...                   ...  ..           ...   ...   ...
5567               ZABELE  PB  8.460345e+04  2018  5288
5568             ZACARIAS  SP  1.705983e+06  2018  5289
5569              ZE DOCA  MA  5.754294e+06  2018  5290
5570               ZORTEA  SC  1.353656e+06  2018  5292
5571                TOTAL   -  1.101598e+12  2018  5004

[5572 rows x 5 columns]

In [ ]:
if "ID" in df_anos[2018].columns:
    total_nulos = df_anos[2018]["ID"].isnull().sum()
    print(f"✅ Total de valores nulos na coluna 'ID': {total_nulos}")
else:
    print("⚠️ A coluna 'ID' não existe no DataFrame de 2018.")

⚠️ A coluna 'ID' não existe no DataFrame de 2018.

In [ ]:
df_anos[2019]

,Município,UF,Ano,Categoria,Arrecadação_GPS,Fonte_x,Arrecadação_DARF,Fonte_y,Arrecadação_Total,Fonte
0,ABADIA DE GOIAS,GO,2019,Arrecadação,3.797903e+06,GPS,12244132.25,DARF,1.604204e+07,Total
1,ABADIA DOS DOURADOS,MG,2019,Arrecadação,4.996573e+06,GPS,4367500.58,DARF,9.364074e+06,Total
2,ABADIANIA,GO,2019,Arrecadação,5.305279e+06,GPS,12388968.52,DARF,1.769425e+07,Total
3,ABAETE,MG,2019,Arrecadação,1.156799e+07,GPS,20403566.51,DARF,3.197155e+07,Total
4,ABAETETUBA,PA,2019,Arrecadação,1.805203e+07,GPS,35750023.16,DARF,5.380205e+07,Total
...,...,...,...,...,...,...,...,...,...,...
5569,ZACARIAS,SP,2019,Arrecadação,8.372400e+05,GPS,1976909.30,DARF,2.814149e+06,Total
5570,ZE DOCA,MA,2019,Arrecadação,4.873864e+06,GPS,7357018.16,DARF,1.223088e+07,Total
5571,ZERADO,-,2019,Arrecadação,2.492127e+04,GPS,NaN,NaN,2.492127e+04,Total
5572,ZORTEA,SC,2019,Arrecadação,2.581880e+06,GPS,1620674.01,DARF,4.202554e+06,Total
5573,{Ñ CLASS},-,2019,Arrecadação,3.007861e+07,GPS,NaN,NaN,3.007861e+07,Total

In [ ]:
if "ID" in df_anos[2019].columns:
    total_nulos = df_anos[2019]["ID"].isnull().sum()
    print(f"✅ Total de valores nulos na coluna 'ID': {total_nulos}")
else:
    print("⚠️ A coluna 'ID' não existe no DataFrame de 2019.")

⚠️ A coluna 'ID' não existe no DataFrame de 2019.

In [ ]:
list20

                Município  UF   Arrecadação   Ano    ID
0         ABADIA DE GOIAS  GO  5.568761e+06  2020     1
1     ABADIA DOS DOURADOS  MG  6.389291e+06  2020     2
2               ABADIANIA  GO  6.815920e+06  2020     3
3                  ABAETE  MG  1.149150e+07  2020     4
4              ABAETETUBA  PA  1.991863e+07  2020     5
...                   ...  ..           ...   ...   ...
5563              ZE DOCA  MA  6.942325e+06  2020  5290
5564               ZERADO   -  1.104825e+10  2020  5291
5565               ZORTEA  SC  2.985098e+06  2020  5292
5566            {Ñ CLASS}   -  3.744781e+07  2020  5293
5567                TOTAL   -  1.576417e+11  2020  5004

[5568 rows x 5 columns]

In [ ]:
list20['ID'].isnull().sum()

np.int64(0)

In [ ]:
list21

                Município  UF   Arrecadação   Ano    ID
0         ABADIA DE GOIAS  GO  5.731301e+06  2021     1
1     ABADIA DOS DOURADOS  MG  5.972473e+06  2021     2
2               ABADIANIA  GO  7.187772e+06  2021     3
3                  ABAETE  MG  1.317147e+07  2021     4
4              ABAETETUBA  PA  3.000272e+07  2021     5
...                   ...  ..           ...   ...   ...
5563              ZE DOCA  MA  8.040389e+06  2021  5290
5564               ZERADO   -  1.242059e+10  2021  5291
5565               ZORTEA  SC  3.068747e+06  2021  5292
5566            {Ñ CLASS}   -  4.076854e+07  2021  5293
5567                TOTAL   -  1.582478e+11  2021  5004

[5568 rows x 5 columns]

In [ ]:
list21['ID'].isnull().sum()

np.int64(0)

In [ ]:
list22

                Município   UF   Arrecadação   Ano    ID
0         ABADIA DE GOIAS   GO  3.413516e+06  2022     1
1     ABADIA DOS DOURADOS   MG  3.490005e+06  2022     2
2               ABADIANIA   GO  3.245343e+06  2022     3
3                  ABAETE   MG  7.044523e+06  2022     4
4              ABAETETUBA   PA  1.887626e+07  2022     5
...                   ...  ...           ...   ...   ...
5563              ZE DOCA   MA  6.594468e+06  2022  5290
5564               ZERADO    -  1.356591e+10  2022  5291
5565               ZORTEA   SC  2.206811e+06  2022  5292
5566            {Ñ CLASS}    -  2.897120e+07  2022  5293
5567                TOTAL  NaN  8.291935e+10  2022  5004

[5568 rows x 5 columns]

In [ ]:
list22['ID'].isnull().sum()

np.int64(0)

In [ ]:
list23

                Município   UF   Arrecadação   Ano    ID
0         ABADIA DE GOIAS   GO  4.839772e+05  2023     1
1     ABADIA DOS DOURADOS   MG  4.277389e+05  2023     2
2               ABADIANIA   GO  6.781606e+05  2023     3
3                  ABAETE   MG  8.788340e+05  2023     4
4              ABAETETUBA   PA  7.834046e+05  2023     5
...                   ...  ...           ...   ...   ...
5547             ZACARIAS   SP  1.397456e+04  2023  5289
5548              ZE DOCA   MA  5.721460e+06  2023  5290
5549               ZORTEA   SC  4.327442e+04  2023  5292
5550            {Ñ CLASS}  NaN  1.996149e+06  2023  5293
5551                TOTAL  NaN  1.366102e+10  2023  5004

[5552 rows x 5 columns]

In [ ]:
list23['ID'].isnull().sum()

np.int64(0)

In [ ]:
import pandas as pd

# Agora temos o mesmo identificador para todas as listas > juntar todos em um painel de dados

df = pd.concat([list17[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], 
                list18[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']],
                list19[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']],
                list20[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']],
                list21[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']],
                list22[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']],
                list23[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']]],
               ignore_index=True)

###df = list17[['ID', 'Município', 'UF', 'Ano', 'Arrecadação' ]].copy()
# Merge 2018
###df = df.merge(list18[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')
# Merge 2019 and following
#df = df.merge(list19[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')
#df = df.merge(list20[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')
#df = df.merge(list21[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')
#df = df.merge(list22[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')
#df = df.merge(list23[['ID', 'Município', 'UF', 'Ano', 'Arrecadação']], on='ID', how='left')

df

In [ ]:
import unidecode

# Padronizar nomes no df
df["Município"] = df["Município"].apply(lambda x: unidecode.unidecode(x).upper().strip())

# Criar a coluna "Nome Alternativo" apenas quando houver diferença
df["Nome Alternativo"] = None  # Inicialmente, definir como None para facilitar a atribuição


# Converter para string antes de padronizar
df_ibge["MUNICÍPIO - IBGE"] = df_ibge["MUNICÍPIO - IBGE"].astype(str)
df_ibge["MUNICÍPIO - IBGE"] = df_ibge["MUNICÍPIO - IBGE"].apply(lambda x: unidecode.unidecode(x).upper())


# Fazer o merge
df_final = df.merge(df_ibge[["MUNICÍPIO - IBGE", "UF", "CÓDIGO DO MUNICÍPIO - IBGE"]],
                    left_on=["Município", "UF"], right_on=["MUNICÍPIO - IBGE", "UF"], how="left")

# Renomear a coluna do código IBGE
df_final.rename(columns={"CÓDIGO DO MUNICÍPIO - IBGE": "Código IBGE"}, inplace=True)

# Definir "Nome Alternativo" apenas quando houver diferença entre os nomes
df_final.loc[df_final["Município"] != df_final["MUNICÍPIO - IBGE"], "Nome Alternativo"] = df_final["Município"]

# Remover a coluna extra "MUNICÍPIO - IBGE" após comparação
df_final.drop(columns=["MUNICÍPIO - IBGE"], inplace=True)

# Exibir resultados
print(df_final[["Município", "Nome Alternativo", "Código IBGE"]].head())
df_final

             Município Nome Alternativo  Código IBGE
0      ABADIA DE GOIAS             None    5200050.0
1  ABADIA DOS DOURADOS             None    3100104.0
2            ABADIANIA             None    5200100.0
3               ABAETE             None    3100203.0
4           ABAETETUBA             None    1500107.0

,ID,Município,UF,Ano,Arrecadação,Nome Alternativo,Código IBGE
0,1,ABADIA DE GOIAS,GO,2005,7.482930e+05,None,5200050.0
1,2,ABADIA DOS DOURADOS,MG,2005,3.778686e+05,None,3100104.0
2,3,ABADIANIA,GO,2005,5.330299e+05,None,5200100.0
3,4,ABAETE,MG,2005,4.179359e+06,None,3100203.0
4,5,ABAETETUBA,PA,2005,2.081937e+06,None,1500107.0
...,...,...,...,...,...,...,...
105827,5289,ZACARIAS,SP,2023,1.397456e+04,None,3557154.0
105828,5290,ZE DOCA,MA,2023,5.721460e+06,None,2114007.0
105829,5292,ZORTEA,SC,2023,4.327442e+04,None,4219853.0
105830,5293,{N CLASS},NaN,2023,1.996149e+06,{N CLASS},NaN
105831,5004,TOTAL,NaN,2023,1.366102e+10,TOTAL,NaN

In [ ]:
# Guardar o número de linhas após o merge
linhas_depois = df_final.shape[0]

# Comparar diferenças
print(f"Linhas antes do merge: {linhas_antes}")
print(f"Linhas depois do merge: {linhas_depois}")

# Verificar municípios que não encontraram correspondência no IBGE
municipios_perdidos = df_final[df_final["Código IBGE"].isna()]
print(f"Municípios sem código IBGE: {municipios_perdidos.shape[0]}")
print(municipios_perdidos.head())

# Caso queira listar os municípios sem correspondência:
municipios_faltando = df[~df["Município"].isin(df_ibge["MUNICÍPIO - IBGE"])]
print(f"Quantidade de municípios no df que não foram encontrados no IBGE: {municipios_faltando.shape[0]}")
print(municipios_faltando.head())

Linhas antes do merge: 105832
Linhas depois do merge: 105832
Municípios sem código IBGE: 715
      ID                Município  UF   Ano  Arrecadação  \
206  198          AMPARO DA SERRA  MG  2005     77166.28
207  199  AMPARO DE SAO FRANCISCO  SE  2005     12390.42
411  395                     ASSU  RN  2005   2230012.49
467  449    BALNEARIO DE PICARRAS  SC  2005   5012133.13
492  473      BARAO DO MONTE ALTO  MG  2005     79439.42

            Nome Alternativo  Código IBGE
206          AMPARO DA SERRA          NaN
207  AMPARO DE SAO FRANCISCO          NaN
411                     ASSU          NaN
467    BALNEARIO DE PICARRAS          NaN
492      BARAO DO MONTE ALTO          NaN
Quantidade de municípios no df que não foram encontrados no IBGE: 645
      ID                Município  UF   Ano  Arrecadação Nome Alternativo
206  198          AMPARO DA SERRA  MG  2005     77166.28             None
207  199  AMPARO DE SAO FRANCISCO  SE  2005     12390.42             None
411  395                     ASSU  RN  2005   2230012.49             None
467  449    BALNEARIO DE PICARRAS  SC  2005   5012133.13             None
492  473      BARAO DO MONTE ALTO  MG  2005     79439.42             None

In [ ]:
from fuzzywuzzy import process

# Criar uma lista de municípios do IBGE com a UF
municipios_ibge_dict = df_ibge.set_index("MUNICÍPIO - IBGE")["UF"].to_dict()

# Verificar correspondências aproximadas para municípios sem código IBGE
for municipio in sorted(municipios_faltando_lista):
    match = process.extractOne(municipio, list(municipios_ibge_dict.keys()), score_cutoff=80)  # Ajuste o score se necessário
    if match:
        uf_match = municipios_ibge_dict[match[0]]  # Recuperar a UF correspondente
        print(f"🔍 '{municipio}' ({df[df['Município'] == municipio]['UF'].values[0]}) pode corresponder a '{match[0]}' ({uf_match}) (similaridade {match[1]}%)")

🔍 'ASSU' (RN) pode corresponder a 'ASSUNCAO DO PIAUI' (PI) (similaridade 90%)
🔍 'BOA SAUDE' (RN) pode corresponder a 'SAUDE' (BA) (similaridade 90%)
🔍 'BOM JESUS' (GO) pode corresponder a 'BOM JESUS' (RS) (similaridade 100%)
🔍 'BRASOPOLIS' (MG) pode corresponder a 'BRAZOPOLIS' (MG) (similaridade 90%)
🔍 'CORONEL SAPUCAIA' (MS) pode corresponder a 'SAPUCAIA' (RJ) (similaridade 90%)
🔍 'DONA EUSEBIA' (MG) pode corresponder a 'DONA EUZEBIA' (MG) (similaridade 92%)
🔍 'EMBU' (SP) pode corresponder a 'EMBU DAS ARTES' (SP) (similaridade 90%)
🔍 'FLORINIA' (SP) pode corresponder a 'FLORANIA' (RN) (similaridade 88%)
🔍 'FORTALEZA DO TABOCAO' (TO) pode corresponder a 'TABOCAO' (TO) (similaridade 90%)
🔍 'IGUARACI' (PE) pode corresponder a 'GUARACI' (PR) (similaridade 93%)
🔍 'MUNHOZ DE MELLO' (PR) pode corresponder a 'MUNHOZ DE MELO' (PR) (similaridade 97%)
🔍 'PARATI' (RJ) pode corresponder a 'PARAI' (RS) (similaridade 91%)
🔍 'PASSA-VINTE' (MG) pode corresponder a 'PASSA VINTE' (MG) (similaridade 100%)
🔍 'POXOREO' (MT) pode corresponder a 'POXOREU' (MT) (similaridade 86%)
🔍 'PRESIDENTE CASTELO BRANCO' (PR) pode corresponder a 'PRESIDENTE CASTELO BRANCO' (PR) (similaridade 100%)
🔍 'SANTA TERESINHA' (BA) pode corresponder a 'SANTA TERESINHA' (PB) (similaridade 100%)
🔍 'SANTAREM' (PA) pode corresponder a 'SANTAREM' (PA) (similaridade 100%)
🔍 'SAO DOMINGOS DE POMBAL' (PB) pode corresponder a 'SAO DOMINGOS' (GO) (similaridade 90%)
🔍 'SAO VALERIO DA NATIVIDADE' (TO) pode corresponder a 'NATIVIDADE' (TO) (similaridade 90%)

In [ ]:
# Criar uma cópia dos nomes originais antes de qualquer alteração
df["Nome Alternativo"] = df["Município"]

# Correções iniciais de formatação (acentos, maiúsculas)
import unidecode
df["Município"] = df["Município"].apply(lambda x: unidecode.unidecode(x).upper().strip())

# Aplicar todas as correções identificadas com fuzzy matching
correcoes = {
    "AMPARO DA SERRA": "AMPARO DO SERRA",
    "AMPARO DE SAO FRANCISCO": "AMPARO DO SAO FRANCISCO",
    "BALNEARIO DE PICARRAS": "BALNEARIO PICARRAS",
    "BARAO DO MONTE ALTO": "BARAO DE MONTE ALTO",
    "BELEM DE SAO FRANCISCO": "BELEM DO SAO FRANCISCO",
    "BIRITIBA-MIRIM": "BIRITIBA MIRIM",
    "BRASOPOLIS": "BRAZOPOLIS",
    "DONA EUSEBIA": "DONA EUZEBIA",
    "ELDORADO DOS CARAJAS": "ELDORADO DO CARAJAS",
    "GRAO PARA": "GRAO-PARA",
    "LAGOA DO ITAENGA": "LAGOA DE ITAENGA",
    "MOGI-MIRIM": "MOGI MIRIM",
    "MUNHOZ DE MELLO": "MUNHOZ DE MELO",
    "MUQUEM DE SAO FRANCISCO": "MUQUEM DO SAO FRANCISCO",
    "NOVA DO MAMORE": "NOVA MAMORE",
    "OLHO D'AGUA DOS BORGES": "OLHO D'AGUA DO BORGES",
    "PASSA-VINTE": "PASSA VINTE",
    "POXOREO": "POXOREU",
    "SANTA CRUZ DO MONTE CASTELO": "SANTA CRUZ DE MONTE CASTELO",
    "SANTA ISABEL DO PARA": "SANTA IZABEL DO PARA",
    "SANTANA DO LIVRAMENTO": "SANT'ANA DO LIVRAMENTO",
    "TRAJANO DE MORAIS": "TRAJANO DE MORAES"
}

df["Município"] = df["Município"].replace(correcoes)

# Refazer o merge com os nomes corrigidos
df_final = df.merge(df_ibge[["MUNICÍPIO - IBGE", "UF", "CÓDIGO DO MUNICÍPIO - IBGE"]],
                    left_on=["Município", "UF"], right_on=["MUNICÍPIO - IBGE", "UF"], how="left")

df_final.rename(columns={"CÓDIGO DO MUNICÍPIO - IBGE": "Código IBGE"}, inplace=True)
df_final.drop(columns=["MUNICÍPIO - IBGE"], inplace=True)

# Verificar as alterações
print(df_final[["Município", "Nome Alternativo", "Código IBGE"]].head())  # Confirma se tudo está correto

             Município     Nome Alternativo  Código IBGE
0      ABADIA DE GOIAS      ABADIA DE GOIAS    5200050.0
1  ABADIA DOS DOURADOS  ABADIA DOS DOURADOS    3100104.0
2            ABADIANIA            ABADIANIA    5200100.0
3               ABAETE               ABAETE    3100203.0
4           ABAETETUBA           ABAETETUBA    1500107.0

In [ ]:
# Guardar o número de linhas antes do merge
linhas_antes = df.shape[0]

# Refazer o merge
df_final = df.merge(df_ibge[["MUNICÍPIO - IBGE", "UF", "CÓDIGO DO MUNICÍPIO - IBGE"]],
                    left_on=["Município", "UF"], right_on=["MUNICÍPIO - IBGE", "UF"], how="left")

df_final.rename(columns={"CÓDIGO DO MUNICÍPIO - IBGE": "Código IBGE"}, inplace=True)
df_final.drop(columns=["MUNICÍPIO - IBGE"], inplace=True)

# Guardar o número de linhas após o merge
linhas_depois = df_final.shape[0]

# Comparar diferenças
print(f"Linhas antes do merge: {linhas_antes}")
print(f"Linhas depois do merge: {linhas_depois}")

# Verificar municípios que ainda não encontraram correspondência no IBGE
municipios_perdidos = df_final[df_final["Código IBGE"].isna()]
print(f"Municípios sem código IBGE: {municipios_perdidos.shape[0]}")
print(municipios_perdidos.head())

# Listar novamente os municípios que não foram encontrados no IBGE
municipios_faltando = df[~df["Município"].isin(df_ibge["MUNICÍPIO - IBGE"])]
print(f"Quantidade de municípios no df que ainda não foram encontrados no IBGE: {municipios_faltando.shape[0]}")
print(municipios_faltando.head())

Linhas antes do merge: 105832
Linhas depois do merge: 105832
Municípios sem código IBGE: 302
        ID         Município  UF   Ano   Arrecadação  Nome Alternativo  \
411    395              ASSU  RN  2005  2.230012e+06              ASSU
638    608         BOA SAUDE  RN  2005  2.390603e+04         BOA SAUDE
674    640         BOM JESUS  GO  2005  3.085056e+06         BOM JESUS
1411  1335  CORONEL SAPUCAIA  MS  2005  4.553153e+05  CORONEL SAPUCAIA
1657  1576              EMBU  SP  2005  1.648743e+08              EMBU

      Código IBGE
411           NaN
638           NaN
674           NaN
1411          NaN
1657          NaN
Quantidade de municípios no df que ainda não foram encontrados no IBGE: 232
        ID         Município  UF   Ano   Arrecadação  Nome Alternativo
411    395              ASSU  RN  2005  2.230012e+06              ASSU
638    608         BOA SAUDE  RN  2005  2.390603e+04         BOA SAUDE
1411  1335  CORONEL SAPUCAIA  MS  2005  4.553153e+05  CORONEL SAPUCAIA
1657  1576              EMBU  SP  2005  1.648743e+08              EMBU
1733  1649          EXTERIOR  EX  2005  2.251857e+08          EXTERIOR