# Lista de Exercícios — Dataframes

Esta lista tem como objetivo praticar os principais recursos construção de Dataframes em Python visto na última aula.

### Tarefa para entregar

* 1. Fazer um Script em Jupyter de um robô de coleta de dados com o Selenium. Ele deve coletar todas as planilhas do site da receita federal, do site:
  * "https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/copy_of_arrecadacao-das-receitas-administradas-pela-rfb-por-municipio"

* 2. No mesmo Script, você deve realizar uma programação completa para unificar todas as planilhas em uma estrutura de dados em painel. 
  * Dicas: Lembre de adicionar uma coluna com o ano da amostra, e uma coluna com um código identificador - Código do IBGE. Verifique o procedimento de criação do identificador que realizamos ao fazer o web scraping com o pandas em aula.

* Entregue o arquivo `.ipynb` por e-mail (daniel.uhr@gmail.com) até o dia **28/04/2024**.

**Bom trabaho!**

In [ ]:
#1.A
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys

# definir local
navegador = webdriver.Chrome()
navegador.get('https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/copy_of_arrecadacao-das-receitas-administradas-pela-rfb-por-municipio')

# Click on cookie message! Otherwise, next code does not execute.
consent_button = navegador.find_element(By.XPATH, "//html/body/div[5]/div/div/div/div/div[2]/button[2]")
consent_button.click()

#print("Check if cookie message disappeared! Otherwise, next code does not execute.")

In [4]:
#1.B
#downloads excel arquives to download folder

from selenium.webdriver.common.by import By

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[1]/th/a').click()
#ate 2017   //*[@id="a5c9477ba62b4003a31cfd35b30d16db"]/div/table/tbody/tr[1]/th/a

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[2]/th/span/a').click()
#2018       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[2]/th/span/a

navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[3]/th/span[1]/a').click()
#2019       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[3]/th/span[1]/a

#2020       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[4]/th/span/span/a[1]
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[4]/th/span/span/a[1]').click()

#2021       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[5]/th/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[5]/th/span/span/a').click()

#2022       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[6]/th/span/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[6]/th/span/span/span/a').click()

#2023       //*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[7]/th/span/span/span/a
navegador.find_element(By.XPATH, '//*[@id="ae554d1500ec47989aa1163a11525b2f"]/div/table/tbody/tr[7]/th/span/span/span/a').click()

In [428]:
# unificar todas as planilhas em uma estrutura de dados em painel. 
#  * Dicas: Lembre de adicionar uma coluna com o ano da amostra, 
#   * e uma coluna com um código identificador - Código do IBGE. 
#   Verifique o procedimento de criação do identificador que realizamos ao fazer o web scraping com o pandas em aula.

import pandas as pd

# Caminho do arquivo
file_path = r"C:\Users\johan\Downloads\arrecadacao-da-receita-administrada-pela-rfb-por-municipio-2005-a-2017.xlsx"

# Ler todas as abas disponíveis no arquivo
abas_disponiveis = pd.ExcelFile(file_path).sheet_names
print(abas_disponiveis)

# Criar um dicionário para armazenar os DataFrames com nomes ajustados
df_dict = {}

# Padronizar manualmente os nomes das abas
for aba in abas_disponiveis:
    aba_formatada = aba.strip()  # Remove espaços extras
    
    if aba_formatada.lower() == "gps":
        aba_padronizada = "GPS"
    elif aba_formatada.lower() == "darf":
        aba_padronizada = "DARF"
    elif aba_formatada.lower() == "total":
        aba_padronizada = "Total"
    else:
        aba_padronizada = aba_formatada  # Mantém outros nomes inalterados
    
    # Ler a aba com o nome original e salvar no dicionário com o nome padronizado
    df_dict[aba_padronizada] = pd.read_excel(file_path, sheet_name=aba, engine="openpyxl", skiprows=5)

# Exibir abas carregadas
df_dict.keys() # Confirma nomes ajustados

['Darf', 'GPS', 'TOTAL']

dict_keys(['DARF', 'GPS', 'Total'])

In [429]:
# Exibir o head de cada aba
for nome_aba, df in df_dict.items():
    print(f"\n🔍 Head da aba '{nome_aba}':")
    print(df.head())

🔍 Head da aba 'DARF':
            MUNICIPIOS  UF        2005        2006        2007        2008  \
0      ABADIA DE GOIAS  GO   748293.01   743933.43   947889.34  1326710.17
1  ABADIA DOS DOURADOS  MG   377868.56   367432.40   448066.69   499392.49
2            ABADIANIA  GO   533029.95   685872.14   863835.95  1230150.65
3               ABAETE  MG  4179358.65  5198049.55  5868576.82  5440673.41
4           ABAETETUBA  PA  2081937.34  2375672.21  2885653.45  3740444.69

         2009        2010        2011         2012         2013         2014  \
0  1481737.43  2380864.09  3643560.50   4534735.71   5877249.54   7841338.72
1   556702.73   683420.91  1207955.63   2743175.80   3267699.57   3291358.53
2  1368021.86  1995984.56  2996679.83   6206806.65   7117866.66   7868537.40
3  5523713.19  6526988.68  8005829.32  11455173.65  13140499.09  14624455.60
4  4868675.36  5224109.14  6967024.70  15160086.13  17680084.77  20342911.70

          2015         2016         2017
0   7305137.10   7600893.50   8634988.28
1   2912465.44   3378452.81   3013558.56
2   8876646.96   7806015.38   8168374.26
3  13284862.67  13782165.70  14282333.27
4  23292622.53  25036288.17  26641427.34

🔍 Head da aba 'GPS':
            MUNICIPIOS  UF          2005          2006          2007  \
0      ABADIA DE GOIAS  GO  6.448262e+05  8.158361e+05  1.130923e+06
1  ABADIA DOS DOURADOS  MG  6.109822e+05  7.572518e+05  8.188743e+05
2            ABADIANIA  GO  7.724839e+05  1.218940e+06  1.040877e+06
3               ABAETE  MG  6.374911e+06  7.621875e+06  8.726543e+06
4           ABAETETUBA  PA  2.675579e+06  3.374748e+06  3.284799e+06

           2008          2009          2010          2011          2012  \
0  1.419805e+06  1.630513e+06  2.312871e+06  2.758747e+06  3.247511e+06
1  9.115607e+05  1.133417e+06  1.342957e+06  1.812994e+06  2.291551e+06
2  1.387549e+06  1.616781e+06  2.400822e+06  3.799320e+06  4.829327e+06
3  9.372551e+06  1.051340e+07  1.120625e+07  1.358436e+07  1.529564e+07
4  3.896137e+06  4.106154e+06  6.045883e+06  8.740851e+06  1.232112e+07

           2013          2014          2015          2016          2017
0  4.225608e+06  3.832148e+06  4.243071e+06  3.845028e+06  4.967659e+06
1  3.323375e+06  2.884321e+06  3.358760e+06  2.409536e+06  3.066581e+06
2  6.514020e+06  5.526478e+06  6.903064e+06  7.256358e+06  7.924757e+06
3  1.539611e+07  1.421678e+07  1.427694e+07  1.563147e+07  1.332954e+07
4  1.608974e+07  1.459249e+07  1.684081e+07  1.785528e+07  1.831995e+07

🔍 Head da aba 'Total':
            MUNICIPIOS  UF          2005          2006          2007  \
0      ABADIA DE GOIAS  GO  1.393119e+06  1.559770e+06  2.078812e+06
1  ABADIA DOS DOURADOS  MG  9.888507e+05  1.124684e+06  1.266941e+06
2            ABADIANIA  GO  1.305514e+06  1.904812e+06  1.904713e+06
3               ABAETE  MG  1.055427e+07  1.281992e+07  1.459512e+07
4           ABAETETUBA  PA  4.757516e+06  5.750420e+06  6.170452e+06

           2008          2009          2010          2011          2012  \
0  2.746515e+06  3.112251e+06  4.693735e+06  6.402307e+06  7.782246e+06
1  1.410953e+06  1.690120e+06  2.026378e+06  3.020950e+06  5.034727e+06
2  2.617699e+06  2.984802e+06  4.396807e+06  6.796000e+06  1.103613e+07
3  1.481322e+07  1.603712e+07  1.773323e+07  2.159019e+07  2.675082e+07
4  7.636582e+06  8.974829e+06  1.126999e+07  1.570788e+07  2.748121e+07

           2013          2014          2015          2016          2017
0  1.010286e+07  1.167349e+07  1.154821e+07  1.144592e+07  1.360265e+07
1  6.591074e+06  6.175680e+06  6.271225e+06  5.787989e+06  6.080139e+06
2  1.363189e+07  1.339501e+07  1.577971e+07  1.506237e+07  1.609313e+07
3  2.853661e+07  2.884124e+07  2.756180e+07  2.941363e+07  2.761187e+07
4  3.376983e+07  3.493540e+07  4.013343e+07  4.289157e+07  4.496137e+07

In [430]:
# Aplicar melt() em todas as abas antes da unificação
for aba, df in df_dict.items():
    print(f"Length {aba}: {len(df)}")
    
    # Padronizar nome das colunas
    df.rename(columns={'MUNICIPIOS': 'Município', 'ARRECADAÇÃO': 'Arrecadação'}, inplace=True)

    # Transformar de wide para long
    df_melted = df.melt(id_vars=["Município", "UF"], var_name="Ano", value_name=f"Arrecadação_{aba}")

    # Gravar de onde vem o valor
    df_melted["Fonte"] = aba

print(df_melted.head)

Length DARF: 5572
Length GPS: 5566
Length Total: 5584
<bound method NDFrame.head of                  Município  UF   Ano  Arrecadação_Total  Fonte
0          ABADIA DE GOIAS  GO  2005       1.393119e+06  Total
1      ABADIA DOS DOURADOS  MG  2005       9.888507e+05  Total
2                ABADIANIA  GO  2005       1.305514e+06  Total
3                   ABAETE  MG  2005       1.055427e+07  Total
4               ABAETETUBA  PA  2005       4.757516e+06  Total
...                    ...  ..   ...                ...    ...
72587               ZABELE  PB  2017       1.539485e+06  Total
72588             ZACARIAS  SP  2017       2.965100e+06  Total
72589              ZE DOCA  MA  2017       8.640173e+06  Total
72590               ZORTEA  SC  2017       3.400539e+06  Total
72591                TOTAL   -  2017       1.279825e+12  Total

[72592 rows x 5 columns]>

In [ ]:
df_melted

In [431]:
# Criar DataFrame inicial vazio
list17 = None

# Aplicar melt() em todas as abas antes da unificação
for aba, df in df_dict.items():
    print(f"Length {aba}: {len(df)}")
    
    # Padronizar nome das colunas
    df.rename(columns={'MUNICIPIOS': 'Município', 'ARRECADAÇÃO': 'Arrecadação'}, inplace=True)

    # Transformar de wide para long
    df_melted = df.melt(id_vars=["Município", "UF"], var_name="Ano", value_name=f"Arrecadação_{aba}")

    # Gravar de onde vem o valor
    df_melted["Fonte"] = aba

    # Unificar corretamente usando merge
    if list17 is None:
        list17 = df_melted  # Primeiro DataFrame define a base
    else:
        list17 = list17.merge(df_melted, on=["Município", "UF", "Ano"], how="outer")

# Verificar os nomes das abas após a importação

print(list17["Ano"].dtype)

Length DARF: 5572
Length GPS: 5566
Length Total: 5584
object

In [ ]:
list17

In [433]:
# Exibir valores únicos para entender o problema
print("🔍 Valores únicos na coluna 'Ano' antes da conversão:")
print(list17["Ano"].unique())

# Converter a coluna 'Ano' para inteiro
list17["Ano"] = pd.to_numeric(list17["Ano"], errors="coerce").astype("Int64")

print("\n✅ Tipo atualizado:", list17["Ano"].dtype)
print(list17["Ano"].unique())  # Verificar os valores únicos novamente

# Exibir resultado final
print("✅ Tipo atualizado:", list17["Ano"].dtype)
print("❌ Quantidade de valores nulos após conversão:", list17["Ano"].isna().sum())

🔍 Valores únicos na coluna 'Ano' antes da conversão:
['2005' '2006' '2007' '2008' '2009' '2010' '2011' '2012' '2013' '2014'
 '2015' '2016' '2017']

✅ Tipo atualizado: Int64
<IntegerArray>
[2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Length: 13, dtype: Int64
✅ Tipo atualizado: Int64
❌ Quantidade de valores nulos após conversão: 0

In [178]:
import pandas as pd

# Lista dos anos disponíveis
anos = [2018, 2019, 2020, 2021, 2022, 2023]

# Criar um dicionário para armazenar os DataFrames de cada ano
df_anos = {}

# Processar todos os arquivos em um loop
for ano in anos:
    print(f"📂 Processando {ano}...")

    # Definir o caminho do arquivo
    file_path = fr"C:\Users\johan\Downloads\arrecadacao-da-receita-administrada-pela-rfb-por-municipio-{ano}.xlsx"

    # Ler todas as abas disponíveis no arquivo
    abas_disponiveis = pd.ExcelFile(file_path).sheet_names

    # Criar um dicionário para armazenar os DataFrames de cada aba do ano
    df_dict = {}

    # Processar cada aba (DARF, GPS, Total)
    for aba in abas_disponiveis:
        aba_formatada = aba.strip()
        
        if aba_formatada.lower() == "gps":
            aba_padronizada = "GPS"
        elif aba_formatada.lower() == "darf":
            aba_padronizada = "DARF"
        elif aba_formatada.lower() == "total":
            aba_padronizada = "Total"
        else:
            aba_padronizada = aba_formatada  

        # Ler cada aba do arquivo e armazenar no dicionário
        df_dict[aba_padronizada] = pd.read_excel(file_path, sheet_name=aba, engine="openpyxl", skiprows=5)

    # Criar DataFrame consolidado para este ano
    df_final = None

    # Aplicar transformação `melt()` em todas as abas antes de armazenar
    for aba, df in df_dict.items():
        print(f"✅ Processando aba {aba} ({ano}): {len(df)} registros")

        # Padronizar nome das colunas
        df.rename(columns={'MUNICÍPIOS': 'Município', 'ARRECADAÇÃO': 'Arrecadação'}, inplace=True)

        # Adicionar a coluna 'Ano'
        df["Ano"] = ano

        # Transformar de wide para long
        df_melted = df.melt(id_vars=["Município", "UF", "Ano"], var_name="Categoria", value_name=f"Arrecadação_{aba}")

        # Gravar de onde vem o valor
        df_melted["Fonte"] = aba

        # Unificar corretamente usando merge
        if df_final is None:
            df_final = df_melted  # Primeiro DataFrame define a base
        else:
            df_final = df_final.merge(df_melted, on=["Município", "UF", "Ano", "Categoria"], how="outer")

    # Armazenar o resultado do ano no dicionário geral
    df_anos[ano] = df_final

    print(f"✅ Dados armazenados para {ano}!")

# Agora, `df_anos[2018]`, `df_anos[2019]`, etc. contêm os DataFrames de cada ano separadamente!

# visualizar
#print(df_anos[2018].head())
#print(df_anos[2019].head())
#print(df_anos[2020].head())
#print(df_anos[2021].head())
#print(df_anos[2022].head())
#print(df_anos[2023].head())

📂 Processando 2018...

C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

✅ Processando aba DARF (2018): 5572 registros
✅ Processando aba GPS (2018): 5568 registros
✅ Processando aba Total (2018): 5578 registros
✅ Dados armazenados para 2018!
📂 Processando 2019...
✅ Processando aba GPS (2019): 5568 registros
✅ Processando aba DARF (2019): 5572 registros
✅ Processando aba Total (2019): 5574 registros
✅ Dados armazenados para 2019!
📂 Processando 2020...
✅ Processando aba GPS (2020): 5568 registros
✅ Processando aba DARF (2020): 5572 registros
✅ Processando aba Total (2020): 5574 registros
✅ Dados armazenados para 2020!
📂 Processando 2021...
✅ Processando aba GPS (2021): 5568 registros
✅ Processando aba DARF (2021): 5572 registros
✅ Processando aba Total (2021): 5574 registros
✅ Dados armazenados para 2021!
📂 Processando 2022...
✅ Processando aba GPS (2022): 5568 registros
✅ Processando aba DARF (2022): 5572 registros
✅ Processando aba Total (2022): 5574 registros
✅ Dados armazenados para 2022!
📂 Processando 2023...
✅ Processando aba GPS (2023): 5552 registros
✅ Processando aba DARF (2023): 5572 registros
✅ Processando aba Total (2023): 5573 registros
✅ Dados armazenados para 2023!

In [179]:
import pandas as pd

print(df_anos.keys())  # Verifique as chaves disponíveis

# Criar um DataFrame separado para cada ano e salvar como df_[ano]
for ano, df in df_anos.items():
    globals()[f"df_{ano}"] = df.copy()  # Define a variável com o nome dinâmico

    # Exibir as primeiras linhas para verificar cada DataFrame
    print(f"🔍 DataFrame do ano {ano}:")
    print(globals()[f"df_{ano}"].head())

dict_keys([2018, 2019, 2020, 2021, 2022, 2023])
🔍 DataFrame do ano 2018:
             Município  UF   Ano    Categoria  Arrecadação_DARF Fonte_x  \
0      ABADIA DE GOIAS  GO  2018  Arrecadação        9509713.49    DARF
1  ABADIA DOS DOURADOS  MG  2018  Arrecadação        3457362.00    DARF
2            ABADIANIA  GO  2018  Arrecadação        8996131.56    DARF
3               ABAETE  MG  2018  Arrecadação       16060311.20    DARF
4           ABAETETUBA  PA  2018  Arrecadação       28281622.15    DARF

   Arrecadação_GPS Fonte_y  Arrecadação_Total  Fonte
0     5.322375e+06     GPS       1.483209e+07  Total
1     5.492808e+06     GPS       8.950170e+06  Total
2     8.795502e+06     GPS       1.779163e+07  Total
3     1.919428e+07     GPS       3.525459e+07  Total
4     3.127840e+07     GPS       5.956002e+07  Total
🔍 DataFrame do ano 2019:
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2019  Arrecadação     3.797903e+06     GPS
1  ABADIA DOS DOURADOS  MG  2019  Arrecadação     4.996573e+06     GPS
2            ABADIANIA  GO  2019  Arrecadação     5.305279e+06     GPS
3               ABAETE  MG  2019  Arrecadação     1.156799e+07     GPS
4           ABAETETUBA  PA  2019  Arrecadação     1.805203e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       12244132.25    DARF       1.604204e+07  Total
1        4367500.58    DARF       9.364074e+06  Total
2       12388968.52    DARF       1.769425e+07  Total
3       20403566.51    DARF       3.197155e+07  Total
4       35750023.16    DARF       5.380205e+07  Total
🔍 DataFrame do ano 2020:
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2020  Arrecadação       5568760.54     GPS
1  ABADIA DOS DOURADOS  MG  2020  Arrecadação       6389291.46     GPS
2            ABADIANIA  GO  2020  Arrecadação       6815920.00     GPS
3               ABAETE  MG  2020  Arrecadação      11491497.62     GPS
4           ABAETETUBA  PA  2020  Arrecadação      19918627.92     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       16515239.27    DARF        22083999.81  Total
1        4575592.99    DARF        10964884.45  Total
2       12512420.49    DARF        19328340.49  Total
3       22971308.59    DARF        34462806.21  Total
4       37645006.50    DARF        57563634.42  Total
🔍 DataFrame do ano 2021:
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2021  Arrecadação     5.731301e+06     GPS
1  ABADIA DOS DOURADOS  MG  2021  Arrecadação     5.972473e+06     GPS
2            ABADIANIA  GO  2021  Arrecadação     7.187772e+06     GPS
3               ABAETE  MG  2021  Arrecadação     1.317147e+07     GPS
4           ABAETETUBA  PA  2021  Arrecadação     3.000272e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       22231269.13    DARF       2.796257e+07  Total
1        5592030.73    DARF       1.156450e+07  Total
2       19656760.35    DARF       2.684453e+07  Total
3       35392549.43    DARF       4.856402e+07  Total
4       46057901.01    DARF       7.606062e+07  Total
🔍 DataFrame do ano 2022:
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2022  Arrecadação     3.413516e+06     GPS
1  ABADIA DOS DOURADOS  MG  2022  Arrecadação     3.490005e+06     GPS
2            ABADIANIA  GO  2022  Arrecadação     3.245343e+06     GPS
3               ABAETE  MG  2022  Arrecadação     7.044523e+06     GPS
4           ABAETETUBA  PA  2022  Arrecadação     1.887626e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       27662996.55    DARF       3.107651e+07  Total
1       10197772.70    DARF       1.368778e+07  Total
2       29146031.22    DARF       3.239137e+07  Total
3       47264200.43    DARF       5.430872e+07  Total
4       70958256.09    DARF       8.983451e+07  Total
🔍 DataFrame do ano 2023:
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2023  Arrecadação        483977.23     GPS
1  ABADIA DOS DOURADOS  MG  2023  Arrecadação        427738.91     GPS
2            ABADIANIA  GO  2023  Arrecadação        678160.63     GPS
3               ABAETE  MG  2023  Arrecadação        878834.04     GPS
4           ABAETETUBA  PA  2023  Arrecadação        783404.63     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       32992856.91    DARF        33476834.14  Total
1       13195865.60    DARF        13623604.51  Total
2       26169372.37    DARF        26847533.00  Total
3       61532280.74    DARF        62411114.78  Total
4       81106448.13    DARF        81889852.76  Total

In [106]:
import pandas as pd


# Adicionar a coluna "Nome_Alternativo" com valores específicos
municipios_master["Nome_Alternativo"] = municipios_master.apply(
    lambda row: "PASSA VINTE" if row["UF"] == "MG" and row["Município"] == "PASSA-VINTE"
    else "PAU D ARCO" if row["UF"] == "PA" and row["Município"] == "PAU D'ARCO"
    else None,
    axis=1
)

# Remover as linhas com os municípios que não devem permanecer
municipios_master = municipios_master[~municipios_master["Município"].isin(["PASSA VINTE", "PAU D ARCO"])]

# Exibir resultado atualizado
print(municipios_master.head())
print(municipios_master.shape[0])

      Município  UF Nome_Alternativo
0         TOTAL   -             None
1    ACRELANDIA  AC             None
2  ASSIS BRASIL  AC             None
3     BRASILEIA  AC             None
4        BUJARI  AC             None
5587

In [103]:
print(municipios_master.head())
print(municipios_master.shape[0])

      Município  UF Nome_Alternativo
0         TOTAL   -             None
1    ACRELANDIA  AC             None
2  ASSIS BRASIL  AC             None
3     BRASILEIA  AC             None
4        BUJARI  AC             None
5587

In [109]:
# Filtrar o DataFrame para encontrar a linha desejada
linha_especifica = municipios_master[ (municipios_master["Município"] == "PASSA-VINTE")]
#(municipios_master["UF"] == "MG") &

# Exibir o resultado
print("🔍 Linha encontrada:")
print(linha_especifica)

🔍 Linha encontrada:
        Município  UF Nome_Alternativo
1908  PASSA-VINTE  MG      PASSA VINTE

In [111]:
print("🔍 Municípios únicos em Nome_Alternativo:")
print(municipios_master["Nome_Alternativo"].dropna().unique())

🔍 Municípios únicos em Nome_Alternativo:
['PASSA VINTE' 'PAU D ARCO']

In [112]:
 # Criar coluna com codigo IGBE

## Raspagem das tabelas do site
url = 'https://www.gov.br/receitafederal/dados/municipios.csv'
df_ibge = pd.read_csv(url, sep=";", encoding="latin1")

print(type(df_ibge))  # Deve ser um pandas DataFrame

## Checando o número e shape de tabelas encontradas
print(df_ibge.shape)  # Retorna (número de linhas, número de colunas)
print(df_ibge.head())

<class 'pandas.core.frame.DataFrame'>
(5571, 5)
   CÓDIGO DO MUNICÍPIO - TOM  CÓDIGO DO MUNICÍPIO - IBGE  \
0                          1                     1100106
1                          2                     1100379
2                          3                     1100205
3                          4                     1100452
4                          5                     1100122

           MUNICÍPIO - TOM         MUNICÍPIO - IBGE  UF
0            GUAJARÁ-MIRIM            Guajará-Mirim  RO
1  ALTO ALEGRE DOS PARECIS  Alto Alegre dos Parecis  RO
2              PORTO VELHO              Porto Velho  RO
3                  BURITIS                  Buritis  RO
4                JI-PARANÁ                Ji-Paraná  RO

In [ ]:
import pandas as pd

# Carregar o CSV dos municípios brasileiros do prof
url = "https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv"
municipios_ibge = pd.read_csv(url)

# Exibir as primeiras linhas
print(municipios_ibge.head())
print(municipios_ibge.shape)  # Retorna (número de linhas, número de colunas)

# Como teria que substituir o codigo_uf pela UF, vou optar por usar a outra lista, ela tbm tem uma linha a mais...?

In [ ]:
from unidecode import unidecode

# Remover todas as colunas que contêm "Codigo_IBGE" no nome
municipios_master = municipios_master.drop(columns=[col for col in municipios_master.columns if "Codigo_IBGE" in col])

# Renomear colunas do df_ibge para facilitar a junção
df_ibge.rename(columns={"CÓDIGO DO MUNICÍPIO - IBGE": "Codigo_IBGE", "MUNICÍPIO - IBGE": "Município", "UF": "UF"}, inplace=True)

# Exibir resultado
print(municipios_master.head())
print(df_ibge)

# Padronizar nome principal do município para comparação
municipios_master["Municipio_Padrao"] = municipios_master["Município"].astype(str).str.strip().str.lower().apply(unidecode)
df_ibge["Municipio_Padrao"] = df_ibge["Município"].astype(str).str.strip().str.lower().apply(unidecode)

# Criar múltiplas colunas para variações de nome, caso ainda não existam
for i in range(1, 5):  # Criando "Nome_Alternativo_1" até "Nome_Alternativo_4"
    col_name = f"Nome_Alternativo_{i}"
    if col_name not in municipios_master.columns:
        municipios_master[col_name] = None  # Inicializar como vazio

# Atualizar a lista de colunas de variações para serem usadas no merge
variacoes = ["Municipio_Padrao"] + [col for col in municipios_master.columns if "Nome_Alternativo" in col]

# Inicializar coluna de Código IBGE
municipios_master["Codigo_IBGE"] = None

# Criar a coluna "Codigo_IBGE" antes do merge para evitar KeyError
if "Codigo_IBGE" not in municipios_master.columns:
    municipios_master["Codigo_IBGE"] = None
    print ("nao tem coluna codigo_IBGE")

print("Antes do merge", municipios_master.columns)

# Fazer o merge usando todas as variações possíveis
#for col in variacoes:
#    municipios_master.loc[municipios_master["Codigo_IBGE"].isna(), "Codigo_IBGE"] = \
#        municipios_master.loc[municipios_master["Codigo_IBGE"].isna()].merge(
#            df_ibge[["Municipio_Padrao", "UF", "Codigo_IBGE"]],
#            left_on=[col, "UF"],
#            right_on=["Municipio_Padrao", "UF"],
#            how="left"
#        )["Codigo_IBGE"]

print("Valores únicos de Municipio_Padrao antes do merge:", municipios_master["Municipio_Padrao"].unique())
print("Valores únicos de UF antes do merge:", municipios_master["UF"].unique())

import numpy as np

for col in variacoes:
    temp_merge = municipios_master.merge(df_ibge[["Municipio_Padrao", "UF", "Codigo_IBGE"]],
                                         left_on=[col, "UF"], right_on=["Municipio_Padrao", "UF"], how="left")

    # Unificar corretamente os códigos IBGE antes da atribuição
    if "Codigo_IBGE_x" in temp_merge.columns and "Codigo_IBGE_y" in temp_merge.columns:
        temp_merge["Codigo_IBGE"] = temp_merge["Codigo_IBGE_x"].combine_first(temp_merge["Codigo_IBGE_y"])
        temp_merge.drop(columns=["Codigo_IBGE_x", "Codigo_IBGE_y"], inplace=True)

    print("Colunas após merge:", temp_merge.columns)  # Testar se a coluna existe

    # Atribuir valores sem sobrescrever diretamente a coluna
    municipios_master.loc[municipios_master["Codigo_IBGE"].isna(), "Codigo_IBGE"] = temp_merge["Codigo_IBGE"].astype("Int64").replace({np.nan: pd.NA})

#print("Depois do merge", municipios_master.columns)

# Unificar as colunas "Codigo_IBGE_x" e "Codigo_IBGE_y"
#municipios_master["Codigo_IBGE"] = municipios_master["Codigo_IBGE_x"].combine_first(municipios_master["Codigo_IBGE_y"])

# Remover as colunas "_x" e "_y" para evitar redundância
#municipios_master.drop(columns=["Codigo_IBGE_x", "Codigo_IBGE_y"], inplace=True)

# Contar quantos municípios ainda ficaram sem código IBGE
total_sem_codigo = municipios_master["Codigo_IBGE"].isna().sum()

# Exibir resultados
print(f"🔍 Total de municípios sem código IBGE após correção: {total_sem_codigo}")
print(municipios_master.head())
#print(df_ibge)

      Município  UF Nome_Alternativo Municipio_Padrao Nome_Alternativo_1  \
0         TOTAL   -             None            total               None
1    ACRELANDIA  AC             None       acrelandia               None
2  ASSIS BRASIL  AC             None     assis brasil               None
3     BRASILEIA  AC             None        brasileia               None
4        BUJARI  AC             None           bujari               None

  Nome_Alternativo_2 Nome_Alternativo_3 Nome_Alternativo_4
0               None               None               None
1               None               None               None
2               None               None               None
3               None               None               None
4               None               None               None
      CÓDIGO DO MUNICÍPIO - TOM  Codigo_IBGE          MUNICÍPIO - TOM  \
0                             1      1100106            GUAJARÁ-MIRIM
1                             2      1100379  ALTO ALEGRE DOS PARECIS
2                             3      1100205              PORTO VELHO
3                             4      1100452                  BURITIS
4                             5      1100122                JI-PARANÁ
...                         ...          ...                      ...
5566                       9989      4217550               SERRA ALTA
5567                       9991      4218756                TUNÁPOLIS
5568                       9993      5209457                 GUARINOS
5569                       9995      5218789               RIO QUENTE
5570                       9997      5003157         CORONEL SAPUCAIA

                    Município  UF         Municipio_Padrao
0               Guajará-Mirim  RO            guajara-mirim
1     Alto Alegre dos Parecis  RO  alto alegre dos parecis
2                 Porto Velho  RO              porto velho
3                     Buritis  RO                  buritis
4                   Ji-Paraná  RO                ji-parana
...                       ...  ..                      ...
5566               Serra Alta  SC               serra alta
5567                Tunápolis  SC                tunapolis
5568                 Guarinos  GO                 guarinos
5569               Rio Quente  GO               rio quente
5570                      NaN  MS                      nan

[5571 rows x 6 columns]
Antes do merge Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Codigo_IBGE'],
      dtype='object')
Valores únicos de Municipio_Padrao antes do merge: ['total' 'acrelandia' 'assis brasil' ... 'joca claudino' 'zerado'
 '{n class}']
Valores únicos de UF antes do merge: ['-' 'AC' 'AL' 'AM' 'AP' 'BA' 'CE' 'DF' 'ES' 'EX' 'GO' 'MA' 'MG' 'MS' 'MT'
 'PA' 'PB' 'PE' 'PI' 'PR' 'RJ' 'RN' 'RO' 'RR' 'RS' 'SC' 'SE' 'SP' 'TO']
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Codigo_IBGE'],
      dtype='object')
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao_x',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Municipio_Padrao_y', 'Codigo_IBGE'],
      dtype='object')
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao_x',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Municipio_Padrao_y', 'Codigo_IBGE'],
      dtype='object')
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao_x',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Municipio_Padrao_y', 'Codigo_IBGE'],
      dtype='object')
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao_x',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Municipio_Padrao_y', 'Codigo_IBGE'],
      dtype='object')
Colunas após merge: Index(['Município', 'UF', 'Nome_Alternativo', 'Municipio_Padrao_x',
       'Nome_Alternativo_1', 'Nome_Alternativo_2', 'Nome_Alternativo_3',
       'Nome_Alternativo_4', 'Municipio_Padrao_y', 'Codigo_IBGE'],
      dtype='object')
🔍 Total de municípios sem código IBGE após correção: 17
      Município  UF Nome_Alternativo Municipio_Padrao Nome_Alternativo_1  \
0         TOTAL   -             None            total               None
1    ACRELANDIA  AC             None       acrelandia               None
2  ASSIS BRASIL  AC             None     assis brasil               None
3     BRASILEIA  AC             None        brasileia               None
4        BUJARI  AC             None           bujari               None

  Nome_Alternativo_2 Nome_Alternativo_3 Nome_Alternativo_4 Codigo_IBGE
0               None               None               None        <NA>
1               None               None               None     1200013
2               None               None               None     1200054
3               None               None               None     1200104
4               None               None               None     1200138

C:\Users\johan\AppData\Local\Temp\ipykernel_31972\797375232.py:57: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  temp_merge["Codigo_IBGE"] = temp_merge["Codigo_IBGE_x"].combine_first(temp_merge["Codigo_IBGE_y"])

In [118]:
print("🔍 Municípios únicos em Municipio_Padrao_y:")
print(temp_merge["Municipio_Padrao_y"].dropna().unique())

# essa coluna esta vazia

print("🔍 Municípios únicos em Municipio_Padrao_x:")
print(temp_merge["Municipio_Padrao_x"].dropna().unique())

# aqui tem todos os municipios

print("🔍 Municípios únicos em Nome_Alternativo:")
print(temp_merge["Nome_Alternativo"].dropna().unique())

print("🔍 Municípios únicos em Nome_Alternativo_1:")
print(temp_merge["Nome_Alternativo_1"].dropna().unique())

print("🔍 Municípios únicos em Nome_Alternativo_2:")
print(temp_merge["Nome_Alternativo_2"].dropna().unique())

print("🔍 Municípios únicos em Nome_Alternativo_3:")
print(temp_merge["Nome_Alternativo_3"].dropna().unique())

print("🔍 Municípios únicos em Nome_Alternativo_4:")
print(temp_merge["Nome_Alternativo_4"].dropna().unique())

🔍 Municípios únicos em Municipio_Padrao_y:
[]
🔍 Municípios únicos em Municipio_Padrao_x:
['total' 'acrelandia' 'assis brasil' ... 'joca claudino' 'zerado'
 '{n class}']
🔍 Municípios únicos em Nome_Alternativo:
['PASSA VINTE' 'PAU D ARCO']
🔍 Municípios únicos em Nome_Alternativo_1:
[]
🔍 Municípios únicos em Nome_Alternativo_2:
[]
🔍 Municípios únicos em Nome_Alternativo_3:
[]
🔍 Municípios únicos em Nome_Alternativo_4:
[]

In [119]:
# Filtrar apenas os municípios que estão sem código IBGE
municipios_sem_ibge = municipios_master[municipios_master["Codigo_IBGE"].isna()]

# Exibir todas as linhas sem código IBGE
print("🔍 Municípios sem código IBGE:")
print(municipios_sem_ibge)

🔍 Municípios sem código IBGE:
                    Município  UF Nome_Alternativo         Municipio_Padrao  \
0                       TOTAL   -             None                    total
437     LIVRAMENTO DO BRUMADO  BA             None    livramento do brumado
472   MUQUEM DE SAO FRANCISCO  BA             None  muquem de sao francisco
548           SANTA TERESINHA  BA             None          santa teresinha
884                  EXTERIOR  EX             None                 exterior
918                 BOM JESUS  GO             None                bom jesus
1376          AMPARO DA SERRA  MG             None          amparo da serra
1408      BARAO DO MONTE ALTO  MG             None      barao do monte alto
1443               BRASOPOLIS  MG             None               brasopolis
1605             DONA EUSEBIA  MG             None             dona eusebia
1711    ITABIRINHA DE MANTENA  MG             None    itabirinha de mantena
5582             WANDERLANDIA  TO             None             wanderlandia
5584                 EXTERIOR   -             None                 exterior
5585            JOCA CLAUDINO  PB             None            joca claudino
5586                    Total   -             None                    total
5587                   ZERADO   -             None                   zerado
5588                {Ñ CLASS}   -             None                {n class}

     Nome_Alternativo_1 Nome_Alternativo_2 Nome_Alternativo_3  \
0                  None               None               None
437                None               None               None
472                None               None               None
548                None               None               None
884                None               None               None
918                None               None               None
1376               None               None               None
1408               None               None               None
1443               None               None               None
1605               None               None               None
1711               None               None               None
5582               None               None               None
5584               None               None               None
5585               None               None               None
5586               None               None               None
5587               None               None               None
5588               None               None               None

     Nome_Alternativo_4 Codigo_IBGE
0                  None        <NA>
437                None        <NA>
472                None        <NA>
548                None        <NA>
884                None        <NA>
918                None        <NA>
1376               None        <NA>
1408               None        <NA>
1443               None        <NA>
1605               None        <NA>
1711               None        <NA>
5582               None        <NA>
5584               None        <NA>
5585               None        <NA>
5586               None        <NA>
5587               None        <NA>
5588               None        <NA>

In [124]:
# Filtrar códigos IBGE que não estão presentes em municipios_master
codigos_nao_usados = df_ibge[~df_ibge["Codigo_IBGE"].isin(municipios_master["Codigo_IBGE"])]

# Exibir a lista de códigos não utilizados
print("🔍 Códigos IBGE sem correspondência:")
print(codigos_nao_usados[["Codigo_IBGE", "Município", "UF"]])

🔍 Códigos IBGE sem correspondência:
      Codigo_IBGE                    Município  UF
343       1708254                      Tabocão  TO
375       1502954          Eldorado do Carajás  PA
509       1505601                    Peixe-Boi  PA
520       2513968                 São Domingos  PB
527       1506500         Santa Izabel do Pará  PA
1376      2400208                          Açu  RN
1426      2405306               Januário Cicco  RN
1458      2408409        Olho d'Água do Borges  RN
1740      2601607       Belém do São Francisco  PE
1793      2606903                     Iguaracy  PE
1809      2608503             Lagoa de Itaenga  PE
2077      2922250      Muquém do São Francisco  BA
2124      2800100      Amparo do São Francisco  SE
2508      2928505              Santa Terezinha  BA
2598      3102506              Amparo do Serra  MG
2628      3105509          Barão de Monte Alto  MG
2662      3108909                   Brazópolis  MG
2802      3122900                 Dona Euzébia  MG
3051      3147808                  Passa Vinte  MG
3511      3303807                       Paraty  RJ
3532      3305901            Trajano de Moraes  RJ
3683      3506607               Biritiba Mirim  SP
3767      3515004               Embu das Artes  SP
3925      3530805                   Mogi Mirim  SP
4409      4116307               Munhoz de Melo  PR
4475      4123303  Santa Cruz de Monte Castelo  PR
4613      4206108                    Grão-Pará  SC
4679      4212809           Balneário Piçarras  SC
4690      4213906   Presidente Castello Branco  SC
4999            0                          NaN  EX
5103      4317103       Sant'Ana do Livramento  RS
5250      5107008                      Poxoréu  MT
5420      1720499                  São Valério  TO
5570      5003157                          NaN  MS

In [126]:
print(codigos_nao_usados.head())
print(codigos_nao_usados.shape)

     CÓDIGO DO MUNICÍPIO - TOM  Codigo_IBGE       MUNICÍPIO - TOM  \
343                        345      1708254  FORTALEZA DO TABOCÃO
375                        377      1502954  ELDORADO DOS CARAJÁS
509                        511      1505601             PEIXE-BOI
520                        522      2513968          SÃO DOMINGOS
527                        529      1506500  SANTA ISABEL DO PARÁ

                Município  UF      Municipio_Padrao
343               Tabocão  TO               tabocao
375   Eldorado do Carajás  PA   eldorado do carajas
509             Peixe-Boi  PA             peixe-boi
520          São Domingos  PB          sao domingos
527  Santa Izabel do Pará  PA  santa izabel do para
(34, 6)

In [127]:
from fuzzywuzzy import process

# Criar lista de municípios que não tiveram código IBGE
municipios_sem_ibge = municipios_master[municipios_master["Codigo_IBGE"].isna()]["Municipio_Padrao"].unique()

# Criar lista de municípios de códigos que não foram usados
municipios_nao_usados = codigos_nao_usados["Municipio_Padrao"].unique()

# Comparação fuzzy entre os dois conjuntos
correspondencias = {mun: process.extractOne(mun, municipios_nao_usados) for mun in municipios_sem_ibge}

# Exibir os municípios sem correspondência e sua melhor correspondência encontrada
print("🔍 Correspondências aproximadas:")
for mun, match in correspondencias.items():
    if match:  # Garante que houve uma correspondência
        print(f"{mun} → {match[0]} (similaridade: {match[1]}%)")

🔍 Correspondências aproximadas:
total → sao valerio (similaridade: 54%)
livramento do brumado → sant'ana do livramento (similaridade: 72%)
muquem de sao francisco → muquem do sao francisco (similaridade: 96%)
santa teresinha → santa terezinha (similaridade: 93%)
exterior → peixe-boi (similaridade: 47%)
bom jesus → olho d'agua do borges (similaridade: 48%)
amparo da serra → amparo do serra (similaridade: 93%)
barao do monte alto → barao de monte alto (similaridade: 95%)
brasopolis → brazopolis (similaridade: 90%)
dona eusebia → dona euzebia (similaridade: 92%)
itabirinha de mantena → munhoz de melo (similaridade: 86%)
wanderlandia → nan (similaridade: 60%)
joca claudino → acu (similaridade: 60%)
zerado → eldorado do carajas (similaridade: 60%)
{n class} → presidente castello branco (similaridade: 64%)

In [129]:
print("🔍 Estrutura dos dados em correspondencias:")
print(correspondencias)

🔍 Estrutura dos dados em correspondencias:
{'total': ('sao valerio', 54), 'livramento do brumado': ("sant'ana do livramento", 72), 'muquem de sao francisco': ('muquem do sao francisco', 96), 'santa teresinha': ('santa terezinha', 93), 'exterior': ('peixe-boi', 47), 'bom jesus': ("olho d'agua do borges", 48), 'amparo da serra': ('amparo do serra', 93), 'barao do monte alto': ('barao de monte alto', 95), 'brasopolis': ('brazopolis', 90), 'dona eusebia': ('dona euzebia', 92), 'itabirinha de mantena': ('munhoz de melo', 86), 'wanderlandia': ('nan', 60), 'joca claudino': ('acu', 60), 'zerado': ('eldorado do carajas', 60), '{n class}': ('presidente castello branco', 64)}

In [130]:
print("🔍 Correspondências aproximadas:")
for municipio_original, (municipio_correspondente, similaridade) in correspondencias.items():
    # Identificar a UF correta do município original
    uf_original = municipios_master.loc[municipios_master["Municipio_Padrao"] == municipio_original, "UF"].values[0]

    # Identificar a UF correta do município correspondente
    uf_correspondente = codigos_nao_usados.loc[codigos_nao_usados["Municipio_Padrao"] == municipio_correspondente, "UF"].values
    uf_correspondente = uf_correspondente[0] if len(uf_correspondente) > 0 else "?"

    print(f"{municipio_original} ({uf_original}) → {municipio_correspondente} ({uf_correspondente}) (similaridade: {similaridade}%)")

🔍 Correspondências aproximadas:
total (-) → sao valerio (TO) (similaridade: 54%)
livramento do brumado (BA) → sant'ana do livramento (RS) (similaridade: 72%)
muquem de sao francisco (BA) → muquem do sao francisco (BA) (similaridade: 96%)
santa teresinha (BA) → santa terezinha (BA) (similaridade: 93%)
exterior (EX) → peixe-boi (PA) (similaridade: 47%)
bom jesus (GO) → olho d'agua do borges (RN) (similaridade: 48%)
amparo da serra (MG) → amparo do serra (MG) (similaridade: 93%)
barao do monte alto (MG) → barao de monte alto (MG) (similaridade: 95%)
brasopolis (MG) → brazopolis (MG) (similaridade: 90%)
dona eusebia (MG) → dona euzebia (MG) (similaridade: 92%)
itabirinha de mantena (MG) → munhoz de melo (PR) (similaridade: 86%)
wanderlandia (TO) → nan (EX) (similaridade: 60%)
joca claudino (PB) → acu (RN) (similaridade: 60%)
zerado (-) → eldorado do carajas (PA) (similaridade: 60%)
{n class} (-) → presidente castello branco (SC) (similaridade: 64%)

In [131]:
# Filtrar apenas correspondências com mais de 90% de similaridade
matches_validos = {orig: match for orig, match in correspondencias.items() if match[1] >= 90}

# Iterar pelos municípios e atualizar no DataFrame
for municipio_original, (municipio_correspondente, similaridade) in matches_validos.items():
    # Encontrar a linha correta no municipios_master
    index_mun = municipios_master.loc[municipios_master["Municipio_Padrao"] == municipio_original].index

    if not index_mun.empty:
        # Adicionar o nome alternativo
        municipios_master.loc[index_mun, "Nome_Alternativo"] = municipio_correspondente

        # Buscar e adicionar o código IBGE correto
        codigo_ibge = codigos_nao_usados.loc[codigos_nao_usados["Municipio_Padrao"] == municipio_correspondente, "Codigo_IBGE"].values
        if len(codigo_ibge) > 0:
            municipios_master.loc[index_mun, "Codigo_IBGE"] = codigo_ibge[0]

# Exibir resultado atualizado
print("🔍 Municípios atualizados:")
print(municipios_master[municipios_master["Municipio_Padrao"].isin(matches_validos.keys())])

🔍 Municípios atualizados:
                    Município  UF         Nome_Alternativo  \
472   MUQUEM DE SAO FRANCISCO  BA  muquem do sao francisco
548           SANTA TERESINHA  BA          santa terezinha
1376          AMPARO DA SERRA  MG          amparo do serra
1408      BARAO DO MONTE ALTO  MG      barao de monte alto
1443               BRASOPOLIS  MG               brazopolis
1605             DONA EUSEBIA  MG             dona euzebia
2741          SANTA TERESINHA  PB          santa terezinha

             Municipio_Padrao Nome_Alternativo_1 Nome_Alternativo_2  \
472   muquem de sao francisco               None               None
548           santa teresinha               None               None
1376          amparo da serra               None               None
1408      barao do monte alto               None               None
1443               brasopolis               None               None
1605             dona eusebia               None               None
2741          santa teresinha               None               None

     Nome_Alternativo_3 Nome_Alternativo_4 Codigo_IBGE
472                None               None     2922250
548                None               None     2928505
1376               None               None     3102506
1408               None               None     3105509
1443               None               None     3108909
1605               None               None     3122900
2741               None               None     2928505

In [132]:
# Filtrar apenas os municípios que estão sem código IBGE
municipios_sem_ibge = municipios_master[municipios_master["Codigo_IBGE"].isna()]

# Exibir todas as linhas sem código IBGE
print("🔍 Municípios sem código IBGE:")
print(municipios_sem_ibge)

🔍 Municípios sem código IBGE:
                  Município  UF Nome_Alternativo       Municipio_Padrao  \
0                     TOTAL   -             None                  total
437   LIVRAMENTO DO BRUMADO  BA             None  livramento do brumado
884                EXTERIOR  EX             None               exterior
918               BOM JESUS  GO             None              bom jesus
1711  ITABIRINHA DE MANTENA  MG             None  itabirinha de mantena
5582           WANDERLANDIA  TO             None           wanderlandia
5584               EXTERIOR   -             None               exterior
5585          JOCA CLAUDINO  PB             None          joca claudino
5586                  Total   -             None                  total
5587                 ZERADO   -             None                 zerado
5588              {Ñ CLASS}   -             None              {n class}

     Nome_Alternativo_1 Nome_Alternativo_2 Nome_Alternativo_3  \
0                  None               None               None
437                None               None               None
884                None               None               None
918                None               None               None
1711               None               None               None
5582               None               None               None
5584               None               None               None
5585               None               None               None
5586               None               None               None
5587               None               None               None
5588               None               None               None

     Nome_Alternativo_4 Codigo_IBGE
0                  None        <NA>
437                None        <NA>
884                None        <NA>
918                None        <NA>
1711               None        <NA>
5582               None        <NA>
5584               None        <NA>
5585               None        <NA>
5586               None        <NA>
5587               None        <NA>
5588               None        <NA>

In [133]:
# Filtrar códigos IBGE que não estão presentes em municipios_master
codigos_nao_usados = df_ibge[~df_ibge["Codigo_IBGE"].isin(municipios_master["Codigo_IBGE"])]

# Exibir a lista de códigos não utilizados
print("🔍 Códigos IBGE sem correspondência:")
print(codigos_nao_usados[["Codigo_IBGE", "Município", "UF"]])

🔍 Códigos IBGE sem correspondência:
      Codigo_IBGE                    Município  UF
343       1708254                      Tabocão  TO
375       1502954          Eldorado do Carajás  PA
509       1505601                    Peixe-Boi  PA
520       2513968                 São Domingos  PB
527       1506500         Santa Izabel do Pará  PA
1376      2400208                          Açu  RN
1426      2405306               Januário Cicco  RN
1458      2408409        Olho d'Água do Borges  RN
1661      2513604         Santana dos Garrotes  PB
1740      2601607       Belém do São Francisco  PE
1793      2606903                     Iguaracy  PE
1809      2608503             Lagoa de Itaenga  PE
2124      2800100      Amparo do São Francisco  SE
3051      3147808                  Passa Vinte  MG
3511      3303807                       Paraty  RJ
3532      3305901            Trajano de Moraes  RJ
3683      3506607               Biritiba Mirim  SP
3767      3515004               Embu das Artes  SP
3925      3530805                   Mogi Mirim  SP
4409      4116307               Munhoz de Melo  PR
4475      4123303  Santa Cruz de Monte Castelo  PR
4613      4206108                    Grão-Pará  SC
4679      4212809           Balneário Piçarras  SC
4690      4213906   Presidente Castello Branco  SC
4999            0                          NaN  EX
5103      4317103       Sant'Ana do Livramento  RS
5250      5107008                      Poxoréu  MT
5420      1720499                  São Valério  TO
5570      5003157                          NaN  MS

In [ ]:
# Filtrar o DataFrame para encontrar a linha desejada
linha_especifica = municipios_master[ (municipios_master["Município"] == "PASSA-VINTE")]
#(municipios_master["UF"] == "MG") &

# Exibir o resultado
print("🔍 Linha encontrada:")
print(linha_especifica)

### ERRO!!!! Temos Passa-Vinte com o codigo de Passabem, ou quer dizer, deu um erro na atribuicao do codigo. Terei que voltar e revisar tudo

🔍 Linha encontrada:
        Município  UF Nome_Alternativo Municipio_Padrao Nome_Alternativo_1  \
1908  PASSA-VINTE  MG      PASSA VINTE      passa-vinte               None

     Nome_Alternativo_2 Nome_Alternativo_3 Nome_Alternativo_4 Codigo_IBGE
1908               None               None               None     3147501

In [381]:
#desisti de fazer minha lista de IBGE por enquanto, e percebi que o uso de varias colunas da muito problema no merge depois. entao vou fazer um formato long
# vou usar a lista do colega que baixei do whatsapp e corrigi no excel manualmente com base em pesquisa no google
ibge_master = pd.read_excel(r"C:\Users\johan\Downloads\COD_IBGE_corrigido.xlsm", sheet_name="Plan3", usecols=[0, 1, 2])

# Renomear uma única coluna
ibge_master.rename(columns={"MUNICIPIOS": "Município", "Código Município Completo" : "Código IBGE"}, inplace=True)

# Exibir as primeiras linhas para confirmar
print(ibge_master.head())
ibge_master

# Converter 'Código IBGE' em ibge_master para garantir compatibilidade
ibge_master["Código IBGE"] = ibge_master["Código IBGE"].astype("Int64")

# Conferir se o tipo está correto
print(f"🔍 Tipo de 'Código IBGE' após ajuste: {ibge_master['Código IBGE'].dtype}")

             Município  UF  Código IBGE
0      ABADIA DE GOIAS  GO      5200050
1  ABADIA DOS DOURADOS  MG      3100104
2            ABADIANIA  GO      5200100
3               ABAETE  MG      3100203
4           ABAETETUBA  PA      1500107
🔍 Tipo de 'Código IBGE' após ajuste: Int64

In [ ]:
### ESSE CODIGO TODO AQUI NAO VAI MAIS PRECISAR pq usei o resultado dele para corrigir o EXCEL

import unidecode  # Biblioteca para remover acentos

# Função para padronizar os nomes
def normalizar_nome(nome):
    return unidecode.unidecode(str(nome).strip().upper())

# Aplicar a função de normalização nas colunas
ibge_master["Nome_Alternativo"] = ibge_master["Nome_Alternativo"].apply(normalizar_nome)
ibge_master["Nome_Alternativo_1"] = ibge_master["Nome_Alternativo_1"].apply(normalizar_nome)

# Exibir valores únicos de Nome_Alternativo
print("\n📝 Valores únicos em 'Nome_Alternativo' do ibge_master:")
print(ibge_master["Nome_Alternativo"].unique())

# Exibir valores únicos de Nome_Alternativo_1
print("\n📝 Valores únicos em 'Nome_Alternativo_1' do ibge_master:")
print(ibge_master["Nome_Alternativo_1"].unique())


# Exibir quantidade total de valores únicos
print(f"\n🔍 Total de valores únicos em 'Nome_Alternativo': {ibge_master['Nome_Alternativo'].nunique()}")
print(f"🔍 Total de valores únicos em 'Nome_Alternativo_1': {ibge_master['Nome_Alternativo_1'].nunique()}")

In [386]:
mun = ibge_master[["Município", "UF"]].dropna().drop_duplicates()
# Exibir quantidade de entradas únicas (linhas)
num_entradas = mun.shape[0]

print(f"🔍 Total de pares únicos de Município e UF: {num_entradas}")

🔍 Total de pares únicos de Município e UF: 5595

In [387]:
cod = ibge_master["Código IBGE"].dropna().drop_duplicates()
cod_entradas = cod.shape[0]

print(f"🔍 Total de códigos IBGE únicos: {cod_entradas}")

### Tem que dar uma diferenca de 20, pq tem 1 valor nulo e 19 codigos com nome alternativo

🔍 Total de códigos IBGE únicos: 5575

In [388]:
list17

,Município,UF,Ano,Arrecadação_DARF,Fonte_x,Arrecadação_GPS,Fonte_y,Arrecadação_Total,Fonte
0,ABADIA DE GOIAS,GO,2005,748293.01,DARF,6.448262e+05,GPS,1.393119e+06,Total
1,ABADIA DE GOIAS,GO,2006,743933.43,DARF,8.158361e+05,GPS,1.559770e+06,Total
2,ABADIA DE GOIAS,GO,2007,947889.34,DARF,1.130923e+06,GPS,2.078812e+06,Total
3,ABADIA DE GOIAS,GO,2008,1326710.17,DARF,1.419805e+06,GPS,2.746515e+06,Total
4,ABADIA DE GOIAS,GO,2009,1481737.43,DARF,1.630513e+06,GPS,3.112251e+06,Total
...,...,...,...,...,...,...,...,...,...
72613,ZORTEA,SC,2013,661654.86,DARF,1.677017e+06,GPS,2.338672e+06,Total
72614,ZORTEA,SC,2014,865452.16,DARF,1.396609e+06,GPS,2.262061e+06,Total
72615,ZORTEA,SC,2015,978847.96,DARF,1.935558e+06,GPS,2.914406e+06,Total
72616,ZORTEA,SC,2016,1076423.34,DARF,1.733237e+06,GPS,2.809660e+06,Total
72617,ZORTEA,SC,2017,1220668.80,DARF,2.179870e+06,GPS,3.400539e+06,Total

In [389]:
# Mesclar ibge_master com list17
df_merged = list17.merge(ibge_master, on=["Município", "UF"], how="left")

print(df_merged.shape)

# Criar uma lista com os municípios que queremos excluir
municipios_para_excluir = ["TOTAL"]

# Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
df_merged = df_merged[~df_merged["Município"].isin(municipios_para_excluir)]

# Exibir resultado
print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_merged.shape}")

# Exibir resultado
print("✅ DataFrame mesclado (list17 + ibge_master):")

print(df_merged.head())

(72618, 10)
✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: (72592, 10)
✅ DataFrame mesclado (list17 + ibge_master):
         Município  UF   Ano  Arrecadação_DARF Fonte_x  Arrecadação_GPS  \
0  ABADIA DE GOIAS  GO  2005         748293.01    DARF        644826.24
1  ABADIA DE GOIAS  GO  2006         743933.43    DARF        815836.10
2  ABADIA DE GOIAS  GO  2007         947889.34    DARF       1130922.71
3  ABADIA DE GOIAS  GO  2008        1326710.17    DARF       1419804.58
4  ABADIA DE GOIAS  GO  2009        1481737.43    DARF       1630513.33

  Fonte_y  Arrecadação_Total  Fonte  Código IBGE
0     GPS         1393119.25  Total      5200050
1     GPS         1559769.53  Total      5200050
2     GPS         2078812.05  Total      5200050
3     GPS         2746514.75  Total      5200050
4     GPS         3112250.76  Total      5200050

In [390]:
# verificar o numero de linhas nulas
df_merged['Código IBGE'].isnull().sum()

np.int64(0)

In [391]:
df_2018

,Município,UF,Ano,Categoria,Arrecadação_DARF,Fonte_x,Arrecadação_GPS,Fonte_y,Arrecadação_Total,Fonte,Código IBGE
0,ABADIA DE GOIAS,GO,2018,Arrecadação,9509713.49,DARF,5.322375e+06,GPS,1.483209e+07,Total,5200050
1,ABADIA DOS DOURADOS,MG,2018,Arrecadação,3457362.00,DARF,5.492808e+06,GPS,8.950170e+06,Total,3100104
2,ABADIANIA,GO,2018,Arrecadação,8996131.56,DARF,8.795502e+06,GPS,1.779163e+07,Total,5200100
3,ABAETE,MG,2018,Arrecadação,16060311.20,DARF,1.919428e+07,GPS,3.525459e+07,Total,3100203
4,ABAETETUBA,PA,2018,Arrecadação,28281622.15,DARF,3.127840e+07,GPS,5.956002e+07,Total,1500107
...,...,...,...,...,...,...,...,...,...,...,...
5574,ZACARIAS,SP,2018,Arrecadação,1705983.29,DARF,1.945994e+06,GPS,3.651978e+06,Total,3557154
5575,ZE DOCA,MA,2018,Arrecadação,5754293.73,DARF,7.505679e+06,GPS,1.325997e+07,Total,2114007
5576,ZERADO,-,2018,Arrecadação,NaN,NaN,1.038097e+10,GPS,1.038097e+10,Total,1010001
5577,ZORTEA,SC,2018,Arrecadação,1353655.77,DARF,2.878104e+06,GPS,4.231760e+06,Total,4219853
5578,{Ñ CLASS},-,2018,Arrecadação,NaN,NaN,5.158633e+07,GPS,5.158633e+07,Total,1010002

In [392]:
import pandas as pd

# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Municipio' contém alguma variação de "total"
df_filtrado = df_2018[df_2018["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2018.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2018 = df_2018[~df_2018["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2018.shape}")

    print(df_2018.head())

✅ Total de municípios encontrados com variações de 'total': 0
Empty DataFrame
Columns: [Município, UF, Ano, Categoria, Arrecadação_DARF, Fonte_x, Arrecadação_GPS, Fonte_y, Arrecadação_Total, Fonte, Código IBGE]
Index: []
(5579, 11)

In [393]:
# Verificar se há algum NaN na coluna 'Municipio'
if df_2018["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2018!")
else:
    print("✅ Nenhum município com NaN encontrado.")

✅ Nenhum município com NaN encontrado.

In [394]:
# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2018[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []

In [395]:
# Adicionar Código IBGE ao df_2018 com base no ibge_master
df_2018 = df_2018.merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left"
)

print("\n✅ Merge realizado! Agora 'Código IBGE' está integrado ao df_2018.")
print(df_2018.head())

✅ Merge realizado! Agora 'Código IBGE' está integrado ao df_2018.
             Município  UF   Ano    Categoria  Arrecadação_DARF Fonte_x  \
0      ABADIA DE GOIAS  GO  2018  Arrecadação        9509713.49    DARF
1  ABADIA DOS DOURADOS  MG  2018  Arrecadação        3457362.00    DARF
2            ABADIANIA  GO  2018  Arrecadação        8996131.56    DARF
3               ABAETE  MG  2018  Arrecadação       16060311.20    DARF
4           ABAETETUBA  PA  2018  Arrecadação       28281622.15    DARF

   Arrecadação_GPS Fonte_y  Arrecadação_Total  Fonte  Código IBGE_x  \
0     5.322375e+06     GPS       1.483209e+07  Total        5200050
1     5.492808e+06     GPS       8.950170e+06  Total        3100104
2     8.795502e+06     GPS       1.779163e+07  Total        5200100
3     1.919428e+07     GPS       3.525459e+07  Total        3100203
4     3.127840e+07     GPS       5.956002e+07  Total        1500107

   Código IBGE_y
0        5200050
1        3100104
2        5200100
3        3100203
4        1500107

In [396]:
# verificar o numero de linhas nulas
df_merged['Código IBGE'].isnull().sum()

np.int64(0)

In [379]:
import pandas as pd

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_merged, df_2018], ignore_index=True)

print("\n✅ Linhas de df_2018 adicionadas ao df_merged com sucesso!")
print(df_final.shape)

✅ Linhas de df_2018 adicionadas ao df_merged com sucesso!
(78171, 11)

In [397]:
df_2019

,Município,UF,Ano,Categoria,Arrecadação_GPS,Fonte_x,Arrecadação_DARF,Fonte_y,Arrecadação_Total,Fonte
0,ABADIA DE GOIAS,GO,2019,Arrecadação,3.797903e+06,GPS,12244132.25,DARF,1.604204e+07,Total
1,ABADIA DOS DOURADOS,MG,2019,Arrecadação,4.996573e+06,GPS,4367500.58,DARF,9.364074e+06,Total
2,ABADIANIA,GO,2019,Arrecadação,5.305279e+06,GPS,12388968.52,DARF,1.769425e+07,Total
3,ABAETE,MG,2019,Arrecadação,1.156799e+07,GPS,20403566.51,DARF,3.197155e+07,Total
4,ABAETETUBA,PA,2019,Arrecadação,1.805203e+07,GPS,35750023.16,DARF,5.380205e+07,Total
...,...,...,...,...,...,...,...,...,...,...
5569,ZACARIAS,SP,2019,Arrecadação,8.372400e+05,GPS,1976909.30,DARF,2.814149e+06,Total
5570,ZE DOCA,MA,2019,Arrecadação,4.873864e+06,GPS,7357018.16,DARF,1.223088e+07,Total
5571,ZERADO,-,2019,Arrecadação,2.492127e+04,GPS,NaN,NaN,2.492127e+04,Total
5572,ZORTEA,SC,2019,Arrecadação,2.581880e+06,GPS,1620674.01,DARF,4.202554e+06,Total
5573,{Ñ CLASS},-,2019,Arrecadação,3.007861e+07,GPS,NaN,NaN,3.007861e+07,Total

In [398]:
# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Municipio' contém alguma variação de "total"
df_filtrado = df_2019[df_2019["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2019.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2019 = df_2019[~df_2019["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2019.shape}")

    print(df_2019.head())

✅ Total de municípios encontrados com variações de 'total': 0
Empty DataFrame
Columns: [Município, UF, Ano, Categoria, Arrecadação_GPS, Fonte_x, Arrecadação_DARF, Fonte_y, Arrecadação_Total, Fonte]
Index: []
(5573, 10)

In [399]:
# Verificar se há algum NaN na coluna 'Municipio'
if df_2019["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2019!")
else:
    print("✅ Nenhum município com NaN encontrado.")

# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2019[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)

✅ Nenhum município com NaN encontrado.

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []

In [402]:
import pandas as pd
print(df_final.shape)
print(df_2019.shape)

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_final, df_2019], ignore_index=True)

print("\n✅ Linhas de df_2019 adicionadas ao df_final com sucesso!")
print(df_final.shape)

(89317, 11)
(5573, 10)

✅ Linhas de df_2019 adicionadas ao df_final com sucesso!
(94890, 11)

In [403]:
# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Municipio' contém alguma variação de "total"
df_filtrado = df_2020[df_2020["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2020.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2020 = df_2020[~df_2020["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2020.shape}")

    print(df_2020.head())

# Verificar se há algum NaN na coluna 'Municipio'
if df_2020["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2020!")
else:
    print("✅ Nenhum município com NaN encontrado.")

# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2020[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)


import pandas as pd
print(df_final.shape)
print(df_2020.shape)

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_final, df_2020], ignore_index=True)

print("\n✅ Linhas de df_2020 adicionadas ao df_final com sucesso!")
print(df_final.shape)

✅ Total de municípios encontrados com variações de 'total': 2
     Município UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
5267     TOTAL  -  2020  Arrecadação     1.576417e+11     GPS
5347     Total  -  2020  Arrecadação              NaN     NaN

      Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
5267      1.271575e+12    DARF                NaN    NaN
5347               NaN     NaN       1.429216e+12  Total
(5575, 10)
✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: (5573, 10)
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2020  Arrecadação       5568760.54     GPS
1  ABADIA DOS DOURADOS  MG  2020  Arrecadação       6389291.46     GPS
2            ABADIANIA  GO  2020  Arrecadação       6815920.00     GPS
3               ABAETE  MG  2020  Arrecadação      11491497.62     GPS
4           ABAETETUBA  PA  2020  Arrecadação      19918627.92     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       16515239.27    DARF        22083999.81  Total
1        4575592.99    DARF        10964884.45  Total
2       12512420.49    DARF        19328340.49  Total
3       22971308.59    DARF        34462806.21  Total
4       37645006.50    DARF        57563634.42  Total
✅ Nenhum município com NaN encontrado.

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []
(94890, 11)
(5573, 10)

✅ Linhas de df_2020 adicionadas ao df_final com sucesso!
(100463, 11)

In [405]:
# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Município' contém alguma variação de "total"
df_filtrado = df_2021[df_2021["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2021.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2021 = df_2021[~df_2021["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2021.shape}")

    print(df_2021.head())

# Verificar se há algum NaN na coluna 'Município'
if df_2021["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2021!")
else:
    print("✅ Nenhum município com NaN encontrado.")

# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2021[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)

import pandas as pd
print(df_final.shape)
print(df_2021.shape)

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_final, df_2021], ignore_index=True)

print("\n✅ Linhas de df_2021 adicionadas ao df_final com sucesso!")
print(df_final.shape)

✅ Total de municípios encontrados com variações de 'total': 1
     Município UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
5267     TOTAL  -  2021  Arrecadação     1.582478e+11     GPS

      Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
5267      1.637047e+12    DARF       1.795294e+12  Total
(5574, 10)
✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: (5573, 10)
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2021  Arrecadação     5.731301e+06     GPS
1  ABADIA DOS DOURADOS  MG  2021  Arrecadação     5.972473e+06     GPS
2            ABADIANIA  GO  2021  Arrecadação     7.187772e+06     GPS
3               ABAETE  MG  2021  Arrecadação     1.317147e+07     GPS
4           ABAETETUBA  PA  2021  Arrecadação     3.000272e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       22231269.13    DARF       2.796257e+07  Total
1        5592030.73    DARF       1.156450e+07  Total
2       19656760.35    DARF       2.684453e+07  Total
3       35392549.43    DARF       4.856402e+07  Total
4       46057901.01    DARF       7.606062e+07  Total
✅ Nenhum município com NaN encontrado.

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []
(100463, 11)
(5573, 10)

✅ Linhas de df_2021 adicionadas ao df_final com sucesso!
(106036, 11)

In [406]:
df_final.head()

,Município,UF,Ano,Arrecadação_DARF,Fonte_x,Arrecadação_GPS,Fonte_y,Arrecadação_Total,Fonte,Código IBGE,Categoria
0,ABADIA DE GOIAS,GO,2005,748293.01,DARF,644826.24,GPS,1393119.25,Total,5200050,NaN
1,ABADIA DE GOIAS,GO,2006,743933.43,DARF,815836.10,GPS,1559769.53,Total,5200050,NaN
2,ABADIA DE GOIAS,GO,2007,947889.34,DARF,1130922.71,GPS,2078812.05,Total,5200050,NaN
3,ABADIA DE GOIAS,GO,2008,1326710.17,DARF,1419804.58,GPS,2746514.75,Total,5200050,NaN
4,ABADIA DE GOIAS,GO,2009,1481737.43,DARF,1630513.33,GPS,3112250.76,Total,5200050,NaN

In [407]:
# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Município' contém alguma variação de "total"
df_filtrado = df_2022[df_2022["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2022.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2022 = df_2022[~df_2022["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2022.shape}")

    print(df_2022.head())

# Verificar se há algum NaN na coluna 'Município'
if df_2022["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2022!")
else:
    print("✅ Nenhum município com NaN encontrado.")

# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2022[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)

import pandas as pd
print(df_final.shape)
print(df_2022.shape)

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_final, df_2022], ignore_index=True)

print("\n✅ Linhas de df_2022 adicionadas ao df_final com sucesso!")
print(df_final.shape)

✅ Total de municípios encontrados com variações de 'total': 2
     Município   UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
5267     TOTAL    -  2022  Arrecadação              NaN     NaN
5268     TOTAL  NaN  2022  Arrecadação     8.291935e+10     GPS

      Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
5267      2.006473e+12    DARF       2.089392e+12  Total
5268               NaN     NaN                NaN    NaN
(5575, 10)
✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: (5573, 10)
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2022  Arrecadação     3.413516e+06     GPS
1  ABADIA DOS DOURADOS  MG  2022  Arrecadação     3.490005e+06     GPS
2            ABADIANIA  GO  2022  Arrecadação     3.245343e+06     GPS
3               ABAETE  MG  2022  Arrecadação     7.044523e+06     GPS
4           ABAETETUBA  PA  2022  Arrecadação     1.887626e+07     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       27662996.55    DARF       3.107651e+07  Total
1       10197772.70    DARF       1.368778e+07  Total
2       29146031.22    DARF       3.239137e+07  Total
3       47264200.43    DARF       5.430872e+07  Total
4       70958256.09    DARF       8.983451e+07  Total
✅ Nenhum município com NaN encontrado.

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []
(106036, 11)
(5573, 10)

✅ Linhas de df_2022 adicionadas ao df_final com sucesso!
(111609, 11)

In [408]:
# Criar uma lista de variações de "total"
municipios_para_excluir = ["TOTAL", "total", "Total"]

# Filtrar linhas onde 'Município' contém alguma variação de "total"
df_filtrado = df_2023[df_2023["Município"].str.contains('|'.join(municipios_para_excluir), case=False, na=False)]

# Exibir o resultado
print(f"\n✅ Total de municípios encontrados com variações de 'total': {df_filtrado.shape[0]}")
print(df_filtrado.head())

print(df_2023.shape)

if df_filtrado.shape[0] != 0:

    # Filtrar o DataFrame, mantendo apenas linhas que NÃO contêm esses municípios
    df_2023 = df_2023[~df_2023["Município"].isin(municipios_para_excluir)]

    # Exibir resultado
    print(f"✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: {df_2023.shape}")

    print(df_2023.head())

# Verificar se há algum NaN na coluna 'Município'
if df_2023["Município"].isna().sum() > 0:
    print("❌ Existem municípios com NaN em df_2023!")
else:
    print("✅ Nenhum município com NaN encontrado.")

# Realizar merge diretamente sem alterar a coluna
pares_correspondencia = df_2023[["Município", "UF"]].drop_duplicates().merge(
    ibge_master[["Município", "UF", "Código IBGE"]],
    on=["Município", "UF"],
    how="left",
    indicator=True
)

# Identificar quais municípios não foram encontrados
municipios_sem_correspondencia = pares_correspondencia[pares_correspondencia["_merge"] == "left_only"][["Município", "UF"]]

print(f"\n❌ Total de municípios sem correspondência: {municipios_sem_correspondencia.shape[0]}")
print(municipios_sem_correspondencia)

import pandas as pd
print(df_final.shape)
print(df_2023.shape)

# Concatenar os DataFrames mantendo todas as colunas
df_final = pd.concat([df_final, df_2023], ignore_index=True)

print("\n✅ Linhas de df_2023 adicionadas ao df_final com sucesso!")
print(df_final.shape)

✅ Total de municípios encontrados com variações de 'total': 1
     Município   UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
5267     TOTAL  NaN  2023  Arrecadação     1.366102e+10     GPS

      Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
5267      2.180148e+12    DARF       2.193809e+12  Total
(5573, 10)
✅ Linhas contendo o TOTAL removidas! Novo tamanho do DataFrame: (5572, 10)
             Município  UF   Ano    Categoria  Arrecadação_GPS Fonte_x  \
0      ABADIA DE GOIAS  GO  2023  Arrecadação        483977.23     GPS
1  ABADIA DOS DOURADOS  MG  2023  Arrecadação        427738.91     GPS
2            ABADIANIA  GO  2023  Arrecadação        678160.63     GPS
3               ABAETE  MG  2023  Arrecadação        878834.04     GPS
4           ABAETETUBA  PA  2023  Arrecadação        783404.63     GPS

   Arrecadação_DARF Fonte_y  Arrecadação_Total  Fonte
0       32992856.91    DARF        33476834.14  Total
1       13195865.60    DARF        13623604.51  Total
2       26169372.37    DARF        26847533.00  Total
3       61532280.74    DARF        62411114.78  Total
4       81106448.13    DARF        81889852.76  Total
✅ Nenhum município com NaN encontrado.

❌ Total de municípios sem correspondência: 0
Empty DataFrame
Columns: [Município, UF]
Index: []
(111609, 11)
(5572, 10)

✅ Linhas de df_2023 adicionadas ao df_final com sucesso!
(117181, 11)

In [410]:
# Exibir valores únicos da coluna 'Categoria'
valores_unicos = df_final["Categoria"].unique()

print("\n🔍 Valores únicos na coluna 'Categoria':")
print(valores_unicos)

# Deletar a coluna 'Categoria'
df_final.drop(columns=["Categoria"], inplace=True)

print("\n✅ A coluna 'Categoria' foi removida!")
print(df_final.head())

🔍 Valores únicos na coluna 'Categoria':
[nan 'Arrecadação']

✅ A coluna 'Categoria' foi removida!
         Município  UF   Ano  Arrecadação_DARF Fonte_x  Arrecadação_GPS  \
0  ABADIA DE GOIAS  GO  2005         748293.01    DARF        644826.24
1  ABADIA DE GOIAS  GO  2006         743933.43    DARF        815836.10
2  ABADIA DE GOIAS  GO  2007         947889.34    DARF       1130922.71
3  ABADIA DE GOIAS  GO  2008        1326710.17    DARF       1419804.58
4  ABADIA DE GOIAS  GO  2009        1481737.43    DARF       1630513.33

  Fonte_y  Arrecadação_Total  Fonte  Código IBGE
0     GPS         1393119.25  Total      5200050
1     GPS         1559769.53  Total      5200050
2     GPS         2078812.05  Total      5200050
3     GPS         2746514.75  Total      5200050
4     GPS         3112250.76  Total      5200050